// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensor"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Sensor is the client for interacting with the Sensor builders.
	Sensor *SensorClient
	// SensorSettings is the client for interacting with the SensorSettings builders.
	SensorSettings *SensorSettingsClient
	// SensorType is the client for interacting with the SensorType builders.
	SensorType *SensorTypeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Sensor = NewSensorClient(c.config)
	c.SensorSettings = NewSensorSettingsClient(c.config)
	c.SensorType = NewSensorTypeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Sensor:         NewSensorClient(cfg),
		SensorSettings: NewSensorSettingsClient(cfg),
		SensorType:     NewSensorTypeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Sensor:         NewSensorClient(cfg),
		SensorSettings: NewSensorSettingsClient(cfg),
		SensorType:     NewSensorTypeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Sensor.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Sensor.Use(hooks...)
	c.SensorSettings.Use(hooks...)
	c.SensorType.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Sensor.Intercept(interceptors...)
	c.SensorSettings.Intercept(interceptors...)
	c.SensorType.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *SensorMutation:
		return c.Sensor.mutate(ctx, m)
	case *SensorSettingsMutation:
		return c.SensorSettings.mutate(ctx, m)
	case *SensorTypeMutation:
		return c.SensorType.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// SensorClient is a client for the Sensor schema.
type SensorClient struct {
	config
}

// NewSensorClient returns a client for the Sensor from the given config.
func NewSensorClient(c config) *SensorClient {
	return &SensorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sensor.Hooks(f(g(h())))`.
func (c *SensorClient) Use(hooks ...Hook) {
	c.hooks.Sensor = append(c.hooks.Sensor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sensor.Intercept(f(g(h())))`.
func (c *SensorClient) Intercept(interceptors ...Interceptor) {
	c.inters.Sensor = append(c.inters.Sensor, interceptors...)
}

// Create returns a builder for creating a Sensor entity.
func (c *SensorClient) Create() *SensorCreate {
	mutation := newSensorMutation(c.config, OpCreate)
	return &SensorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Sensor entities.
func (c *SensorClient) CreateBulk(builders ...*SensorCreate) *SensorCreateBulk {
	return &SensorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SensorClient) MapCreateBulk(slice any, setFunc func(*SensorCreate, int)) *SensorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SensorCreateBulk{err: fmt.Errorf("calling to SensorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SensorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SensorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Sensor.
func (c *SensorClient) Update() *SensorUpdate {
	mutation := newSensorMutation(c.config, OpUpdate)
	return &SensorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SensorClient) UpdateOne(s *Sensor) *SensorUpdateOne {
	mutation := newSensorMutation(c.config, OpUpdateOne, withSensor(s))
	return &SensorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SensorClient) UpdateOneID(id int) *SensorUpdateOne {
	mutation := newSensorMutation(c.config, OpUpdateOne, withSensorID(id))
	return &SensorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Sensor.
func (c *SensorClient) Delete() *SensorDelete {
	mutation := newSensorMutation(c.config, OpDelete)
	return &SensorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SensorClient) DeleteOne(s *Sensor) *SensorDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SensorClient) DeleteOneID(id int) *SensorDeleteOne {
	builder := c.Delete().Where(sensor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SensorDeleteOne{builder}
}

// Query returns a query builder for Sensor.
func (c *SensorClient) Query() *SensorQuery {
	return &SensorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSensor},
		inters: c.Interceptors(),
	}
}

// Get returns a Sensor entity by its id.
func (c *SensorClient) Get(ctx context.Context, id int) (*Sensor, error) {
	return c.Query().Where(sensor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SensorClient) GetX(ctx context.Context, id int) *Sensor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryType queries the type edge of a Sensor.
func (c *SensorClient) QueryType(s *Sensor) *SensorTypeQuery {
	query := (&SensorTypeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sensor.Table, sensor.FieldID, id),
			sqlgraph.To(sensortype.Table, sensortype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sensor.TypeTable, sensor.TypeColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SensorClient) Hooks() []Hook {
	return c.hooks.Sensor
}

// Interceptors returns the client interceptors.
func (c *SensorClient) Interceptors() []Interceptor {
	return c.inters.Sensor
}

func (c *SensorClient) mutate(ctx context.Context, m *SensorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SensorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SensorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SensorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SensorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Sensor mutation op: %q", m.Op())
	}
}

// SensorSettingsClient is a client for the SensorSettings schema.
type SensorSettingsClient struct {
	config
}

// NewSensorSettingsClient returns a client for the SensorSettings from the given config.
func NewSensorSettingsClient(c config) *SensorSettingsClient {
	return &SensorSettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sensorsettings.Hooks(f(g(h())))`.
func (c *SensorSettingsClient) Use(hooks ...Hook) {
	c.hooks.SensorSettings = append(c.hooks.SensorSettings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sensorsettings.Intercept(f(g(h())))`.
func (c *SensorSettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.SensorSettings = append(c.inters.SensorSettings, interceptors...)
}

// Create returns a builder for creating a SensorSettings entity.
func (c *SensorSettingsClient) Create() *SensorSettingsCreate {
	mutation := newSensorSettingsMutation(c.config, OpCreate)
	return &SensorSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SensorSettings entities.
func (c *SensorSettingsClient) CreateBulk(builders ...*SensorSettingsCreate) *SensorSettingsCreateBulk {
	return &SensorSettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SensorSettingsClient) MapCreateBulk(slice any, setFunc func(*SensorSettingsCreate, int)) *SensorSettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SensorSettingsCreateBulk{err: fmt.Errorf("calling to SensorSettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SensorSettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SensorSettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SensorSettings.
func (c *SensorSettingsClient) Update() *SensorSettingsUpdate {
	mutation := newSensorSettingsMutation(c.config, OpUpdate)
	return &SensorSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SensorSettingsClient) UpdateOne(ss *SensorSettings) *SensorSettingsUpdateOne {
	mutation := newSensorSettingsMutation(c.config, OpUpdateOne, withSensorSettings(ss))
	return &SensorSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SensorSettingsClient) UpdateOneID(id int) *SensorSettingsUpdateOne {
	mutation := newSensorSettingsMutation(c.config, OpUpdateOne, withSensorSettingsID(id))
	return &SensorSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SensorSettings.
func (c *SensorSettingsClient) Delete() *SensorSettingsDelete {
	mutation := newSensorSettingsMutation(c.config, OpDelete)
	return &SensorSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SensorSettingsClient) DeleteOne(ss *SensorSettings) *SensorSettingsDeleteOne {
	return c.DeleteOneID(ss.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SensorSettingsClient) DeleteOneID(id int) *SensorSettingsDeleteOne {
	builder := c.Delete().Where(sensorsettings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SensorSettingsDeleteOne{builder}
}

// Query returns a query builder for SensorSettings.
func (c *SensorSettingsClient) Query() *SensorSettingsQuery {
	return &SensorSettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSensorSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a SensorSettings entity by its id.
func (c *SensorSettingsClient) Get(ctx context.Context, id int) (*SensorSettings, error) {
	return c.Query().Where(sensorsettings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SensorSettingsClient) GetX(ctx context.Context, id int) *SensorSettings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySensorType queries the sensor_type edge of a SensorSettings.
func (c *SensorSettingsClient) QuerySensorType(ss *SensorSettings) *SensorTypeQuery {
	query := (&SensorTypeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ss.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sensorsettings.Table, sensorsettings.FieldID, id),
			sqlgraph.To(sensortype.Table, sensortype.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, sensorsettings.SensorTypeTable, sensorsettings.SensorTypeColumn),
		)
		fromV = sqlgraph.Neighbors(ss.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SensorSettingsClient) Hooks() []Hook {
	return c.hooks.SensorSettings
}

// Interceptors returns the client interceptors.
func (c *SensorSettingsClient) Interceptors() []Interceptor {
	return c.inters.SensorSettings
}

func (c *SensorSettingsClient) mutate(ctx context.Context, m *SensorSettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SensorSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SensorSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SensorSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SensorSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SensorSettings mutation op: %q", m.Op())
	}
}

// SensorTypeClient is a client for the SensorType schema.
type SensorTypeClient struct {
	config
}

// NewSensorTypeClient returns a client for the SensorType from the given config.
func NewSensorTypeClient(c config) *SensorTypeClient {
	return &SensorTypeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sensortype.Hooks(f(g(h())))`.
func (c *SensorTypeClient) Use(hooks ...Hook) {
	c.hooks.SensorType = append(c.hooks.SensorType, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sensortype.Intercept(f(g(h())))`.
func (c *SensorTypeClient) Intercept(interceptors ...Interceptor) {
	c.inters.SensorType = append(c.inters.SensorType, interceptors...)
}

// Create returns a builder for creating a SensorType entity.
func (c *SensorTypeClient) Create() *SensorTypeCreate {
	mutation := newSensorTypeMutation(c.config, OpCreate)
	return &SensorTypeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SensorType entities.
func (c *SensorTypeClient) CreateBulk(builders ...*SensorTypeCreate) *SensorTypeCreateBulk {
	return &SensorTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SensorTypeClient) MapCreateBulk(slice any, setFunc func(*SensorTypeCreate, int)) *SensorTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SensorTypeCreateBulk{err: fmt.Errorf("calling to SensorTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SensorTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SensorTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SensorType.
func (c *SensorTypeClient) Update() *SensorTypeUpdate {
	mutation := newSensorTypeMutation(c.config, OpUpdate)
	return &SensorTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SensorTypeClient) UpdateOne(st *SensorType) *SensorTypeUpdateOne {
	mutation := newSensorTypeMutation(c.config, OpUpdateOne, withSensorType(st))
	return &SensorTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SensorTypeClient) UpdateOneID(id int) *SensorTypeUpdateOne {
	mutation := newSensorTypeMutation(c.config, OpUpdateOne, withSensorTypeID(id))
	return &SensorTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SensorType.
func (c *SensorTypeClient) Delete() *SensorTypeDelete {
	mutation := newSensorTypeMutation(c.config, OpDelete)
	return &SensorTypeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SensorTypeClient) DeleteOne(st *SensorType) *SensorTypeDeleteOne {
	return c.DeleteOneID(st.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SensorTypeClient) DeleteOneID(id int) *SensorTypeDeleteOne {
	builder := c.Delete().Where(sensortype.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SensorTypeDeleteOne{builder}
}

// Query returns a query builder for SensorType.
func (c *SensorTypeClient) Query() *SensorTypeQuery {
	return &SensorTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSensorType},
		inters: c.Interceptors(),
	}
}

// Get returns a SensorType entity by its id.
func (c *SensorTypeClient) Get(ctx context.Context, id int) (*SensorType, error) {
	return c.Query().Where(sensortype.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SensorTypeClient) GetX(ctx context.Context, id int) *SensorType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySensors queries the sensors edge of a SensorType.
func (c *SensorTypeClient) QuerySensors(st *SensorType) *SensorQuery {
	query := (&SensorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := st.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sensortype.Table, sensortype.FieldID, id),
			sqlgraph.To(sensor.Table, sensor.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sensortype.SensorsTable, sensortype.SensorsColumn),
		)
		fromV = sqlgraph.Neighbors(st.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySettings queries the settings edge of a SensorType.
func (c *SensorTypeClient) QuerySettings(st *SensorType) *SensorSettingsQuery {
	query := (&SensorSettingsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := st.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sensortype.Table, sensortype.FieldID, id),
			sqlgraph.To(sensorsettings.Table, sensorsettings.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, sensortype.SettingsTable, sensortype.SettingsColumn),
		)
		fromV = sqlgraph.Neighbors(st.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SensorTypeClient) Hooks() []Hook {
	return c.hooks.SensorType
}

// Interceptors returns the client interceptors.
func (c *SensorTypeClient) Interceptors() []Interceptor {
	return c.inters.SensorType
}

func (c *SensorTypeClient) mutate(ctx context.Context, m *SensorTypeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SensorTypeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SensorTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SensorTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SensorTypeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SensorType mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Sensor, SensorSettings, SensorType []ent.Hook
	}
	inters struct {
		Sensor, SensorSettings, SensorType []ent.Interceptor
	}
)
