// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/predicate"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensor"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSensor         = "Sensor"
	TypeSensorSettings = "SensorSettings"
	TypeSensorType     = "SensorType"
)

// SensorMutation represents an operation that mutates the Sensor nodes in the graph.
type SensorMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	location      *string
	description   *string
	active        *bool
	last_updated  *time.Time
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	_type         *int
	cleared_type  bool
	done          bool
	oldValue      func(context.Context) (*Sensor, error)
	predicates    []predicate.Sensor
}

var _ ent.Mutation = (*SensorMutation)(nil)

// sensorOption allows management of the mutation configuration using functional options.
type sensorOption func(*SensorMutation)

// newSensorMutation creates new mutation for the Sensor entity.
func newSensorMutation(c config, op Op, opts ...sensorOption) *SensorMutation {
	m := &SensorMutation{
		config:        c,
		op:            op,
		typ:           TypeSensor,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSensorID sets the ID field of the mutation.
func withSensorID(id int) sensorOption {
	return func(m *SensorMutation) {
		var (
			err   error
			once  sync.Once
			value *Sensor
		)
		m.oldValue = func(ctx context.Context) (*Sensor, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Sensor.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSensor sets the old Sensor of the mutation.
func withSensor(node *Sensor) sensorOption {
	return func(m *SensorMutation) {
		m.oldValue = func(context.Context) (*Sensor, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SensorMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SensorMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SensorMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SensorMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Sensor.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SensorMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SensorMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Sensor entity.
// If the Sensor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SensorMutation) ResetName() {
	m.name = nil
}

// SetLocation sets the "location" field.
func (m *SensorMutation) SetLocation(s string) {
	m.location = &s
}

// Location returns the value of the "location" field in the mutation.
func (m *SensorMutation) Location() (r string, exists bool) {
	v := m.location
	if v == nil {
		return
	}
	return *v, true
}

// OldLocation returns the old "location" field's value of the Sensor entity.
// If the Sensor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorMutation) OldLocation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLocation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLocation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLocation: %w", err)
	}
	return oldValue.Location, nil
}

// ClearLocation clears the value of the "location" field.
func (m *SensorMutation) ClearLocation() {
	m.location = nil
	m.clearedFields[sensor.FieldLocation] = struct{}{}
}

// LocationCleared returns if the "location" field was cleared in this mutation.
func (m *SensorMutation) LocationCleared() bool {
	_, ok := m.clearedFields[sensor.FieldLocation]
	return ok
}

// ResetLocation resets all changes to the "location" field.
func (m *SensorMutation) ResetLocation() {
	m.location = nil
	delete(m.clearedFields, sensor.FieldLocation)
}

// SetDescription sets the "description" field.
func (m *SensorMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *SensorMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Sensor entity.
// If the Sensor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *SensorMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[sensor.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *SensorMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[sensor.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *SensorMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, sensor.FieldDescription)
}

// SetActive sets the "active" field.
func (m *SensorMutation) SetActive(b bool) {
	m.active = &b
}

// Active returns the value of the "active" field in the mutation.
func (m *SensorMutation) Active() (r bool, exists bool) {
	v := m.active
	if v == nil {
		return
	}
	return *v, true
}

// OldActive returns the old "active" field's value of the Sensor entity.
// If the Sensor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorMutation) OldActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActive: %w", err)
	}
	return oldValue.Active, nil
}

// ResetActive resets all changes to the "active" field.
func (m *SensorMutation) ResetActive() {
	m.active = nil
}

// SetLastUpdated sets the "last_updated" field.
func (m *SensorMutation) SetLastUpdated(t time.Time) {
	m.last_updated = &t
}

// LastUpdated returns the value of the "last_updated" field in the mutation.
func (m *SensorMutation) LastUpdated() (r time.Time, exists bool) {
	v := m.last_updated
	if v == nil {
		return
	}
	return *v, true
}

// OldLastUpdated returns the old "last_updated" field's value of the Sensor entity.
// If the Sensor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorMutation) OldLastUpdated(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastUpdated is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastUpdated requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastUpdated: %w", err)
	}
	return oldValue.LastUpdated, nil
}

// ClearLastUpdated clears the value of the "last_updated" field.
func (m *SensorMutation) ClearLastUpdated() {
	m.last_updated = nil
	m.clearedFields[sensor.FieldLastUpdated] = struct{}{}
}

// LastUpdatedCleared returns if the "last_updated" field was cleared in this mutation.
func (m *SensorMutation) LastUpdatedCleared() bool {
	_, ok := m.clearedFields[sensor.FieldLastUpdated]
	return ok
}

// ResetLastUpdated resets all changes to the "last_updated" field.
func (m *SensorMutation) ResetLastUpdated() {
	m.last_updated = nil
	delete(m.clearedFields, sensor.FieldLastUpdated)
}

// SetCreatedAt sets the "created_at" field.
func (m *SensorMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SensorMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Sensor entity.
// If the Sensor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SensorMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *SensorMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *SensorMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Sensor entity.
// If the Sensor object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *SensorMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTypeID sets the "type" edge to the SensorType entity by id.
func (m *SensorMutation) SetTypeID(id int) {
	m._type = &id
}

// ClearType clears the "type" edge to the SensorType entity.
func (m *SensorMutation) ClearType() {
	m.cleared_type = true
}

// TypeCleared reports if the "type" edge to the SensorType entity was cleared.
func (m *SensorMutation) TypeCleared() bool {
	return m.cleared_type
}

// TypeID returns the "type" edge ID in the mutation.
func (m *SensorMutation) TypeID() (id int, exists bool) {
	if m._type != nil {
		return *m._type, true
	}
	return
}

// TypeIDs returns the "type" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TypeID instead. It exists only for internal usage by the builders.
func (m *SensorMutation) TypeIDs() (ids []int) {
	if id := m._type; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetType resets all changes to the "type" edge.
func (m *SensorMutation) ResetType() {
	m._type = nil
	m.cleared_type = false
}

// Where appends a list predicates to the SensorMutation builder.
func (m *SensorMutation) Where(ps ...predicate.Sensor) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SensorMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SensorMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Sensor, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SensorMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SensorMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Sensor).
func (m *SensorMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SensorMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.name != nil {
		fields = append(fields, sensor.FieldName)
	}
	if m.location != nil {
		fields = append(fields, sensor.FieldLocation)
	}
	if m.description != nil {
		fields = append(fields, sensor.FieldDescription)
	}
	if m.active != nil {
		fields = append(fields, sensor.FieldActive)
	}
	if m.last_updated != nil {
		fields = append(fields, sensor.FieldLastUpdated)
	}
	if m.created_at != nil {
		fields = append(fields, sensor.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, sensor.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SensorMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sensor.FieldName:
		return m.Name()
	case sensor.FieldLocation:
		return m.Location()
	case sensor.FieldDescription:
		return m.Description()
	case sensor.FieldActive:
		return m.Active()
	case sensor.FieldLastUpdated:
		return m.LastUpdated()
	case sensor.FieldCreatedAt:
		return m.CreatedAt()
	case sensor.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SensorMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sensor.FieldName:
		return m.OldName(ctx)
	case sensor.FieldLocation:
		return m.OldLocation(ctx)
	case sensor.FieldDescription:
		return m.OldDescription(ctx)
	case sensor.FieldActive:
		return m.OldActive(ctx)
	case sensor.FieldLastUpdated:
		return m.OldLastUpdated(ctx)
	case sensor.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case sensor.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Sensor field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SensorMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sensor.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case sensor.FieldLocation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLocation(v)
		return nil
	case sensor.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case sensor.FieldActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActive(v)
		return nil
	case sensor.FieldLastUpdated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastUpdated(v)
		return nil
	case sensor.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case sensor.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Sensor field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SensorMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SensorMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SensorMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Sensor numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SensorMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(sensor.FieldLocation) {
		fields = append(fields, sensor.FieldLocation)
	}
	if m.FieldCleared(sensor.FieldDescription) {
		fields = append(fields, sensor.FieldDescription)
	}
	if m.FieldCleared(sensor.FieldLastUpdated) {
		fields = append(fields, sensor.FieldLastUpdated)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SensorMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SensorMutation) ClearField(name string) error {
	switch name {
	case sensor.FieldLocation:
		m.ClearLocation()
		return nil
	case sensor.FieldDescription:
		m.ClearDescription()
		return nil
	case sensor.FieldLastUpdated:
		m.ClearLastUpdated()
		return nil
	}
	return fmt.Errorf("unknown Sensor nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SensorMutation) ResetField(name string) error {
	switch name {
	case sensor.FieldName:
		m.ResetName()
		return nil
	case sensor.FieldLocation:
		m.ResetLocation()
		return nil
	case sensor.FieldDescription:
		m.ResetDescription()
		return nil
	case sensor.FieldActive:
		m.ResetActive()
		return nil
	case sensor.FieldLastUpdated:
		m.ResetLastUpdated()
		return nil
	case sensor.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case sensor.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Sensor field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SensorMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._type != nil {
		edges = append(edges, sensor.EdgeType)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SensorMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case sensor.EdgeType:
		if id := m._type; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SensorMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SensorMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SensorMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_type {
		edges = append(edges, sensor.EdgeType)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SensorMutation) EdgeCleared(name string) bool {
	switch name {
	case sensor.EdgeType:
		return m.cleared_type
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SensorMutation) ClearEdge(name string) error {
	switch name {
	case sensor.EdgeType:
		m.ClearType()
		return nil
	}
	return fmt.Errorf("unknown Sensor unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SensorMutation) ResetEdge(name string) error {
	switch name {
	case sensor.EdgeType:
		m.ResetType()
		return nil
	}
	return fmt.Errorf("unknown Sensor edge %s", name)
}

// SensorSettingsMutation represents an operation that mutates the SensorSettings nodes in the graph.
type SensorSettingsMutation struct {
	config
	op                          Op
	typ                         string
	id                          *int
	polling_interval_seconds    *int
	addpolling_interval_seconds *int
	min_value                   *float64
	addmin_value                *float64
	max_value                   *float64
	addmax_value                *float64
	mean_value                  *float64
	addmean_value               *float64
	std_deviation               *float64
	addstd_deviation            *float64
	drift_factor                *float64
	adddrift_factor             *float64
	seasonal_variation          *bool
	cycle_period_seconds        *int
	addcycle_period_seconds     *int
	noise_factor                *float64
	addnoise_factor             *float64
	possible_values             *[]string
	appendpossible_values       []string
	anomaly_config              *map[string]interface{}
	clearedFields               map[string]struct{}
	sensor_type                 *int
	clearedsensor_type          bool
	done                        bool
	oldValue                    func(context.Context) (*SensorSettings, error)
	predicates                  []predicate.SensorSettings
}

var _ ent.Mutation = (*SensorSettingsMutation)(nil)

// sensorsettingsOption allows management of the mutation configuration using functional options.
type sensorsettingsOption func(*SensorSettingsMutation)

// newSensorSettingsMutation creates new mutation for the SensorSettings entity.
func newSensorSettingsMutation(c config, op Op, opts ...sensorsettingsOption) *SensorSettingsMutation {
	m := &SensorSettingsMutation{
		config:        c,
		op:            op,
		typ:           TypeSensorSettings,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSensorSettingsID sets the ID field of the mutation.
func withSensorSettingsID(id int) sensorsettingsOption {
	return func(m *SensorSettingsMutation) {
		var (
			err   error
			once  sync.Once
			value *SensorSettings
		)
		m.oldValue = func(ctx context.Context) (*SensorSettings, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SensorSettings.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSensorSettings sets the old SensorSettings of the mutation.
func withSensorSettings(node *SensorSettings) sensorsettingsOption {
	return func(m *SensorSettingsMutation) {
		m.oldValue = func(context.Context) (*SensorSettings, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SensorSettingsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SensorSettingsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SensorSettingsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SensorSettingsMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SensorSettings.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPollingIntervalSeconds sets the "polling_interval_seconds" field.
func (m *SensorSettingsMutation) SetPollingIntervalSeconds(i int) {
	m.polling_interval_seconds = &i
	m.addpolling_interval_seconds = nil
}

// PollingIntervalSeconds returns the value of the "polling_interval_seconds" field in the mutation.
func (m *SensorSettingsMutation) PollingIntervalSeconds() (r int, exists bool) {
	v := m.polling_interval_seconds
	if v == nil {
		return
	}
	return *v, true
}

// OldPollingIntervalSeconds returns the old "polling_interval_seconds" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldPollingIntervalSeconds(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPollingIntervalSeconds is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPollingIntervalSeconds requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPollingIntervalSeconds: %w", err)
	}
	return oldValue.PollingIntervalSeconds, nil
}

// AddPollingIntervalSeconds adds i to the "polling_interval_seconds" field.
func (m *SensorSettingsMutation) AddPollingIntervalSeconds(i int) {
	if m.addpolling_interval_seconds != nil {
		*m.addpolling_interval_seconds += i
	} else {
		m.addpolling_interval_seconds = &i
	}
}

// AddedPollingIntervalSeconds returns the value that was added to the "polling_interval_seconds" field in this mutation.
func (m *SensorSettingsMutation) AddedPollingIntervalSeconds() (r int, exists bool) {
	v := m.addpolling_interval_seconds
	if v == nil {
		return
	}
	return *v, true
}

// ResetPollingIntervalSeconds resets all changes to the "polling_interval_seconds" field.
func (m *SensorSettingsMutation) ResetPollingIntervalSeconds() {
	m.polling_interval_seconds = nil
	m.addpolling_interval_seconds = nil
}

// SetMinValue sets the "min_value" field.
func (m *SensorSettingsMutation) SetMinValue(f float64) {
	m.min_value = &f
	m.addmin_value = nil
}

// MinValue returns the value of the "min_value" field in the mutation.
func (m *SensorSettingsMutation) MinValue() (r float64, exists bool) {
	v := m.min_value
	if v == nil {
		return
	}
	return *v, true
}

// OldMinValue returns the old "min_value" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldMinValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMinValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMinValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMinValue: %w", err)
	}
	return oldValue.MinValue, nil
}

// AddMinValue adds f to the "min_value" field.
func (m *SensorSettingsMutation) AddMinValue(f float64) {
	if m.addmin_value != nil {
		*m.addmin_value += f
	} else {
		m.addmin_value = &f
	}
}

// AddedMinValue returns the value that was added to the "min_value" field in this mutation.
func (m *SensorSettingsMutation) AddedMinValue() (r float64, exists bool) {
	v := m.addmin_value
	if v == nil {
		return
	}
	return *v, true
}

// ClearMinValue clears the value of the "min_value" field.
func (m *SensorSettingsMutation) ClearMinValue() {
	m.min_value = nil
	m.addmin_value = nil
	m.clearedFields[sensorsettings.FieldMinValue] = struct{}{}
}

// MinValueCleared returns if the "min_value" field was cleared in this mutation.
func (m *SensorSettingsMutation) MinValueCleared() bool {
	_, ok := m.clearedFields[sensorsettings.FieldMinValue]
	return ok
}

// ResetMinValue resets all changes to the "min_value" field.
func (m *SensorSettingsMutation) ResetMinValue() {
	m.min_value = nil
	m.addmin_value = nil
	delete(m.clearedFields, sensorsettings.FieldMinValue)
}

// SetMaxValue sets the "max_value" field.
func (m *SensorSettingsMutation) SetMaxValue(f float64) {
	m.max_value = &f
	m.addmax_value = nil
}

// MaxValue returns the value of the "max_value" field in the mutation.
func (m *SensorSettingsMutation) MaxValue() (r float64, exists bool) {
	v := m.max_value
	if v == nil {
		return
	}
	return *v, true
}

// OldMaxValue returns the old "max_value" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldMaxValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMaxValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMaxValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMaxValue: %w", err)
	}
	return oldValue.MaxValue, nil
}

// AddMaxValue adds f to the "max_value" field.
func (m *SensorSettingsMutation) AddMaxValue(f float64) {
	if m.addmax_value != nil {
		*m.addmax_value += f
	} else {
		m.addmax_value = &f
	}
}

// AddedMaxValue returns the value that was added to the "max_value" field in this mutation.
func (m *SensorSettingsMutation) AddedMaxValue() (r float64, exists bool) {
	v := m.addmax_value
	if v == nil {
		return
	}
	return *v, true
}

// ClearMaxValue clears the value of the "max_value" field.
func (m *SensorSettingsMutation) ClearMaxValue() {
	m.max_value = nil
	m.addmax_value = nil
	m.clearedFields[sensorsettings.FieldMaxValue] = struct{}{}
}

// MaxValueCleared returns if the "max_value" field was cleared in this mutation.
func (m *SensorSettingsMutation) MaxValueCleared() bool {
	_, ok := m.clearedFields[sensorsettings.FieldMaxValue]
	return ok
}

// ResetMaxValue resets all changes to the "max_value" field.
func (m *SensorSettingsMutation) ResetMaxValue() {
	m.max_value = nil
	m.addmax_value = nil
	delete(m.clearedFields, sensorsettings.FieldMaxValue)
}

// SetMeanValue sets the "mean_value" field.
func (m *SensorSettingsMutation) SetMeanValue(f float64) {
	m.mean_value = &f
	m.addmean_value = nil
}

// MeanValue returns the value of the "mean_value" field in the mutation.
func (m *SensorSettingsMutation) MeanValue() (r float64, exists bool) {
	v := m.mean_value
	if v == nil {
		return
	}
	return *v, true
}

// OldMeanValue returns the old "mean_value" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldMeanValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMeanValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMeanValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMeanValue: %w", err)
	}
	return oldValue.MeanValue, nil
}

// AddMeanValue adds f to the "mean_value" field.
func (m *SensorSettingsMutation) AddMeanValue(f float64) {
	if m.addmean_value != nil {
		*m.addmean_value += f
	} else {
		m.addmean_value = &f
	}
}

// AddedMeanValue returns the value that was added to the "mean_value" field in this mutation.
func (m *SensorSettingsMutation) AddedMeanValue() (r float64, exists bool) {
	v := m.addmean_value
	if v == nil {
		return
	}
	return *v, true
}

// ClearMeanValue clears the value of the "mean_value" field.
func (m *SensorSettingsMutation) ClearMeanValue() {
	m.mean_value = nil
	m.addmean_value = nil
	m.clearedFields[sensorsettings.FieldMeanValue] = struct{}{}
}

// MeanValueCleared returns if the "mean_value" field was cleared in this mutation.
func (m *SensorSettingsMutation) MeanValueCleared() bool {
	_, ok := m.clearedFields[sensorsettings.FieldMeanValue]
	return ok
}

// ResetMeanValue resets all changes to the "mean_value" field.
func (m *SensorSettingsMutation) ResetMeanValue() {
	m.mean_value = nil
	m.addmean_value = nil
	delete(m.clearedFields, sensorsettings.FieldMeanValue)
}

// SetStdDeviation sets the "std_deviation" field.
func (m *SensorSettingsMutation) SetStdDeviation(f float64) {
	m.std_deviation = &f
	m.addstd_deviation = nil
}

// StdDeviation returns the value of the "std_deviation" field in the mutation.
func (m *SensorSettingsMutation) StdDeviation() (r float64, exists bool) {
	v := m.std_deviation
	if v == nil {
		return
	}
	return *v, true
}

// OldStdDeviation returns the old "std_deviation" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldStdDeviation(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStdDeviation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStdDeviation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStdDeviation: %w", err)
	}
	return oldValue.StdDeviation, nil
}

// AddStdDeviation adds f to the "std_deviation" field.
func (m *SensorSettingsMutation) AddStdDeviation(f float64) {
	if m.addstd_deviation != nil {
		*m.addstd_deviation += f
	} else {
		m.addstd_deviation = &f
	}
}

// AddedStdDeviation returns the value that was added to the "std_deviation" field in this mutation.
func (m *SensorSettingsMutation) AddedStdDeviation() (r float64, exists bool) {
	v := m.addstd_deviation
	if v == nil {
		return
	}
	return *v, true
}

// ClearStdDeviation clears the value of the "std_deviation" field.
func (m *SensorSettingsMutation) ClearStdDeviation() {
	m.std_deviation = nil
	m.addstd_deviation = nil
	m.clearedFields[sensorsettings.FieldStdDeviation] = struct{}{}
}

// StdDeviationCleared returns if the "std_deviation" field was cleared in this mutation.
func (m *SensorSettingsMutation) StdDeviationCleared() bool {
	_, ok := m.clearedFields[sensorsettings.FieldStdDeviation]
	return ok
}

// ResetStdDeviation resets all changes to the "std_deviation" field.
func (m *SensorSettingsMutation) ResetStdDeviation() {
	m.std_deviation = nil
	m.addstd_deviation = nil
	delete(m.clearedFields, sensorsettings.FieldStdDeviation)
}

// SetDriftFactor sets the "drift_factor" field.
func (m *SensorSettingsMutation) SetDriftFactor(f float64) {
	m.drift_factor = &f
	m.adddrift_factor = nil
}

// DriftFactor returns the value of the "drift_factor" field in the mutation.
func (m *SensorSettingsMutation) DriftFactor() (r float64, exists bool) {
	v := m.drift_factor
	if v == nil {
		return
	}
	return *v, true
}

// OldDriftFactor returns the old "drift_factor" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldDriftFactor(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDriftFactor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDriftFactor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDriftFactor: %w", err)
	}
	return oldValue.DriftFactor, nil
}

// AddDriftFactor adds f to the "drift_factor" field.
func (m *SensorSettingsMutation) AddDriftFactor(f float64) {
	if m.adddrift_factor != nil {
		*m.adddrift_factor += f
	} else {
		m.adddrift_factor = &f
	}
}

// AddedDriftFactor returns the value that was added to the "drift_factor" field in this mutation.
func (m *SensorSettingsMutation) AddedDriftFactor() (r float64, exists bool) {
	v := m.adddrift_factor
	if v == nil {
		return
	}
	return *v, true
}

// ResetDriftFactor resets all changes to the "drift_factor" field.
func (m *SensorSettingsMutation) ResetDriftFactor() {
	m.drift_factor = nil
	m.adddrift_factor = nil
}

// SetSeasonalVariation sets the "seasonal_variation" field.
func (m *SensorSettingsMutation) SetSeasonalVariation(b bool) {
	m.seasonal_variation = &b
}

// SeasonalVariation returns the value of the "seasonal_variation" field in the mutation.
func (m *SensorSettingsMutation) SeasonalVariation() (r bool, exists bool) {
	v := m.seasonal_variation
	if v == nil {
		return
	}
	return *v, true
}

// OldSeasonalVariation returns the old "seasonal_variation" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldSeasonalVariation(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeasonalVariation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeasonalVariation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeasonalVariation: %w", err)
	}
	return oldValue.SeasonalVariation, nil
}

// ResetSeasonalVariation resets all changes to the "seasonal_variation" field.
func (m *SensorSettingsMutation) ResetSeasonalVariation() {
	m.seasonal_variation = nil
}

// SetCyclePeriodSeconds sets the "cycle_period_seconds" field.
func (m *SensorSettingsMutation) SetCyclePeriodSeconds(i int) {
	m.cycle_period_seconds = &i
	m.addcycle_period_seconds = nil
}

// CyclePeriodSeconds returns the value of the "cycle_period_seconds" field in the mutation.
func (m *SensorSettingsMutation) CyclePeriodSeconds() (r int, exists bool) {
	v := m.cycle_period_seconds
	if v == nil {
		return
	}
	return *v, true
}

// OldCyclePeriodSeconds returns the old "cycle_period_seconds" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldCyclePeriodSeconds(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCyclePeriodSeconds is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCyclePeriodSeconds requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCyclePeriodSeconds: %w", err)
	}
	return oldValue.CyclePeriodSeconds, nil
}

// AddCyclePeriodSeconds adds i to the "cycle_period_seconds" field.
func (m *SensorSettingsMutation) AddCyclePeriodSeconds(i int) {
	if m.addcycle_period_seconds != nil {
		*m.addcycle_period_seconds += i
	} else {
		m.addcycle_period_seconds = &i
	}
}

// AddedCyclePeriodSeconds returns the value that was added to the "cycle_period_seconds" field in this mutation.
func (m *SensorSettingsMutation) AddedCyclePeriodSeconds() (r int, exists bool) {
	v := m.addcycle_period_seconds
	if v == nil {
		return
	}
	return *v, true
}

// ClearCyclePeriodSeconds clears the value of the "cycle_period_seconds" field.
func (m *SensorSettingsMutation) ClearCyclePeriodSeconds() {
	m.cycle_period_seconds = nil
	m.addcycle_period_seconds = nil
	m.clearedFields[sensorsettings.FieldCyclePeriodSeconds] = struct{}{}
}

// CyclePeriodSecondsCleared returns if the "cycle_period_seconds" field was cleared in this mutation.
func (m *SensorSettingsMutation) CyclePeriodSecondsCleared() bool {
	_, ok := m.clearedFields[sensorsettings.FieldCyclePeriodSeconds]
	return ok
}

// ResetCyclePeriodSeconds resets all changes to the "cycle_period_seconds" field.
func (m *SensorSettingsMutation) ResetCyclePeriodSeconds() {
	m.cycle_period_seconds = nil
	m.addcycle_period_seconds = nil
	delete(m.clearedFields, sensorsettings.FieldCyclePeriodSeconds)
}

// SetNoiseFactor sets the "noise_factor" field.
func (m *SensorSettingsMutation) SetNoiseFactor(f float64) {
	m.noise_factor = &f
	m.addnoise_factor = nil
}

// NoiseFactor returns the value of the "noise_factor" field in the mutation.
func (m *SensorSettingsMutation) NoiseFactor() (r float64, exists bool) {
	v := m.noise_factor
	if v == nil {
		return
	}
	return *v, true
}

// OldNoiseFactor returns the old "noise_factor" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldNoiseFactor(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNoiseFactor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNoiseFactor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNoiseFactor: %w", err)
	}
	return oldValue.NoiseFactor, nil
}

// AddNoiseFactor adds f to the "noise_factor" field.
func (m *SensorSettingsMutation) AddNoiseFactor(f float64) {
	if m.addnoise_factor != nil {
		*m.addnoise_factor += f
	} else {
		m.addnoise_factor = &f
	}
}

// AddedNoiseFactor returns the value that was added to the "noise_factor" field in this mutation.
func (m *SensorSettingsMutation) AddedNoiseFactor() (r float64, exists bool) {
	v := m.addnoise_factor
	if v == nil {
		return
	}
	return *v, true
}

// ResetNoiseFactor resets all changes to the "noise_factor" field.
func (m *SensorSettingsMutation) ResetNoiseFactor() {
	m.noise_factor = nil
	m.addnoise_factor = nil
}

// SetPossibleValues sets the "possible_values" field.
func (m *SensorSettingsMutation) SetPossibleValues(s []string) {
	m.possible_values = &s
	m.appendpossible_values = nil
}

// PossibleValues returns the value of the "possible_values" field in the mutation.
func (m *SensorSettingsMutation) PossibleValues() (r []string, exists bool) {
	v := m.possible_values
	if v == nil {
		return
	}
	return *v, true
}

// OldPossibleValues returns the old "possible_values" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldPossibleValues(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPossibleValues is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPossibleValues requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPossibleValues: %w", err)
	}
	return oldValue.PossibleValues, nil
}

// AppendPossibleValues adds s to the "possible_values" field.
func (m *SensorSettingsMutation) AppendPossibleValues(s []string) {
	m.appendpossible_values = append(m.appendpossible_values, s...)
}

// AppendedPossibleValues returns the list of values that were appended to the "possible_values" field in this mutation.
func (m *SensorSettingsMutation) AppendedPossibleValues() ([]string, bool) {
	if len(m.appendpossible_values) == 0 {
		return nil, false
	}
	return m.appendpossible_values, true
}

// ClearPossibleValues clears the value of the "possible_values" field.
func (m *SensorSettingsMutation) ClearPossibleValues() {
	m.possible_values = nil
	m.appendpossible_values = nil
	m.clearedFields[sensorsettings.FieldPossibleValues] = struct{}{}
}

// PossibleValuesCleared returns if the "possible_values" field was cleared in this mutation.
func (m *SensorSettingsMutation) PossibleValuesCleared() bool {
	_, ok := m.clearedFields[sensorsettings.FieldPossibleValues]
	return ok
}

// ResetPossibleValues resets all changes to the "possible_values" field.
func (m *SensorSettingsMutation) ResetPossibleValues() {
	m.possible_values = nil
	m.appendpossible_values = nil
	delete(m.clearedFields, sensorsettings.FieldPossibleValues)
}

// SetAnomalyConfig sets the "anomaly_config" field.
func (m *SensorSettingsMutation) SetAnomalyConfig(value map[string]interface{}) {
	m.anomaly_config = &value
}

// AnomalyConfig returns the value of the "anomaly_config" field in the mutation.
func (m *SensorSettingsMutation) AnomalyConfig() (r map[string]interface{}, exists bool) {
	v := m.anomaly_config
	if v == nil {
		return
	}
	return *v, true
}

// OldAnomalyConfig returns the old "anomaly_config" field's value of the SensorSettings entity.
// If the SensorSettings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorSettingsMutation) OldAnomalyConfig(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAnomalyConfig is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAnomalyConfig requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAnomalyConfig: %w", err)
	}
	return oldValue.AnomalyConfig, nil
}

// ClearAnomalyConfig clears the value of the "anomaly_config" field.
func (m *SensorSettingsMutation) ClearAnomalyConfig() {
	m.anomaly_config = nil
	m.clearedFields[sensorsettings.FieldAnomalyConfig] = struct{}{}
}

// AnomalyConfigCleared returns if the "anomaly_config" field was cleared in this mutation.
func (m *SensorSettingsMutation) AnomalyConfigCleared() bool {
	_, ok := m.clearedFields[sensorsettings.FieldAnomalyConfig]
	return ok
}

// ResetAnomalyConfig resets all changes to the "anomaly_config" field.
func (m *SensorSettingsMutation) ResetAnomalyConfig() {
	m.anomaly_config = nil
	delete(m.clearedFields, sensorsettings.FieldAnomalyConfig)
}

// SetSensorTypeID sets the "sensor_type" edge to the SensorType entity by id.
func (m *SensorSettingsMutation) SetSensorTypeID(id int) {
	m.sensor_type = &id
}

// ClearSensorType clears the "sensor_type" edge to the SensorType entity.
func (m *SensorSettingsMutation) ClearSensorType() {
	m.clearedsensor_type = true
}

// SensorTypeCleared reports if the "sensor_type" edge to the SensorType entity was cleared.
func (m *SensorSettingsMutation) SensorTypeCleared() bool {
	return m.clearedsensor_type
}

// SensorTypeID returns the "sensor_type" edge ID in the mutation.
func (m *SensorSettingsMutation) SensorTypeID() (id int, exists bool) {
	if m.sensor_type != nil {
		return *m.sensor_type, true
	}
	return
}

// SensorTypeIDs returns the "sensor_type" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// SensorTypeID instead. It exists only for internal usage by the builders.
func (m *SensorSettingsMutation) SensorTypeIDs() (ids []int) {
	if id := m.sensor_type; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSensorType resets all changes to the "sensor_type" edge.
func (m *SensorSettingsMutation) ResetSensorType() {
	m.sensor_type = nil
	m.clearedsensor_type = false
}

// Where appends a list predicates to the SensorSettingsMutation builder.
func (m *SensorSettingsMutation) Where(ps ...predicate.SensorSettings) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SensorSettingsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SensorSettingsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SensorSettings, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SensorSettingsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SensorSettingsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SensorSettings).
func (m *SensorSettingsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SensorSettingsMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.polling_interval_seconds != nil {
		fields = append(fields, sensorsettings.FieldPollingIntervalSeconds)
	}
	if m.min_value != nil {
		fields = append(fields, sensorsettings.FieldMinValue)
	}
	if m.max_value != nil {
		fields = append(fields, sensorsettings.FieldMaxValue)
	}
	if m.mean_value != nil {
		fields = append(fields, sensorsettings.FieldMeanValue)
	}
	if m.std_deviation != nil {
		fields = append(fields, sensorsettings.FieldStdDeviation)
	}
	if m.drift_factor != nil {
		fields = append(fields, sensorsettings.FieldDriftFactor)
	}
	if m.seasonal_variation != nil {
		fields = append(fields, sensorsettings.FieldSeasonalVariation)
	}
	if m.cycle_period_seconds != nil {
		fields = append(fields, sensorsettings.FieldCyclePeriodSeconds)
	}
	if m.noise_factor != nil {
		fields = append(fields, sensorsettings.FieldNoiseFactor)
	}
	if m.possible_values != nil {
		fields = append(fields, sensorsettings.FieldPossibleValues)
	}
	if m.anomaly_config != nil {
		fields = append(fields, sensorsettings.FieldAnomalyConfig)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SensorSettingsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sensorsettings.FieldPollingIntervalSeconds:
		return m.PollingIntervalSeconds()
	case sensorsettings.FieldMinValue:
		return m.MinValue()
	case sensorsettings.FieldMaxValue:
		return m.MaxValue()
	case sensorsettings.FieldMeanValue:
		return m.MeanValue()
	case sensorsettings.FieldStdDeviation:
		return m.StdDeviation()
	case sensorsettings.FieldDriftFactor:
		return m.DriftFactor()
	case sensorsettings.FieldSeasonalVariation:
		return m.SeasonalVariation()
	case sensorsettings.FieldCyclePeriodSeconds:
		return m.CyclePeriodSeconds()
	case sensorsettings.FieldNoiseFactor:
		return m.NoiseFactor()
	case sensorsettings.FieldPossibleValues:
		return m.PossibleValues()
	case sensorsettings.FieldAnomalyConfig:
		return m.AnomalyConfig()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SensorSettingsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sensorsettings.FieldPollingIntervalSeconds:
		return m.OldPollingIntervalSeconds(ctx)
	case sensorsettings.FieldMinValue:
		return m.OldMinValue(ctx)
	case sensorsettings.FieldMaxValue:
		return m.OldMaxValue(ctx)
	case sensorsettings.FieldMeanValue:
		return m.OldMeanValue(ctx)
	case sensorsettings.FieldStdDeviation:
		return m.OldStdDeviation(ctx)
	case sensorsettings.FieldDriftFactor:
		return m.OldDriftFactor(ctx)
	case sensorsettings.FieldSeasonalVariation:
		return m.OldSeasonalVariation(ctx)
	case sensorsettings.FieldCyclePeriodSeconds:
		return m.OldCyclePeriodSeconds(ctx)
	case sensorsettings.FieldNoiseFactor:
		return m.OldNoiseFactor(ctx)
	case sensorsettings.FieldPossibleValues:
		return m.OldPossibleValues(ctx)
	case sensorsettings.FieldAnomalyConfig:
		return m.OldAnomalyConfig(ctx)
	}
	return nil, fmt.Errorf("unknown SensorSettings field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SensorSettingsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sensorsettings.FieldPollingIntervalSeconds:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPollingIntervalSeconds(v)
		return nil
	case sensorsettings.FieldMinValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMinValue(v)
		return nil
	case sensorsettings.FieldMaxValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMaxValue(v)
		return nil
	case sensorsettings.FieldMeanValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMeanValue(v)
		return nil
	case sensorsettings.FieldStdDeviation:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStdDeviation(v)
		return nil
	case sensorsettings.FieldDriftFactor:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDriftFactor(v)
		return nil
	case sensorsettings.FieldSeasonalVariation:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeasonalVariation(v)
		return nil
	case sensorsettings.FieldCyclePeriodSeconds:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCyclePeriodSeconds(v)
		return nil
	case sensorsettings.FieldNoiseFactor:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNoiseFactor(v)
		return nil
	case sensorsettings.FieldPossibleValues:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPossibleValues(v)
		return nil
	case sensorsettings.FieldAnomalyConfig:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAnomalyConfig(v)
		return nil
	}
	return fmt.Errorf("unknown SensorSettings field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SensorSettingsMutation) AddedFields() []string {
	var fields []string
	if m.addpolling_interval_seconds != nil {
		fields = append(fields, sensorsettings.FieldPollingIntervalSeconds)
	}
	if m.addmin_value != nil {
		fields = append(fields, sensorsettings.FieldMinValue)
	}
	if m.addmax_value != nil {
		fields = append(fields, sensorsettings.FieldMaxValue)
	}
	if m.addmean_value != nil {
		fields = append(fields, sensorsettings.FieldMeanValue)
	}
	if m.addstd_deviation != nil {
		fields = append(fields, sensorsettings.FieldStdDeviation)
	}
	if m.adddrift_factor != nil {
		fields = append(fields, sensorsettings.FieldDriftFactor)
	}
	if m.addcycle_period_seconds != nil {
		fields = append(fields, sensorsettings.FieldCyclePeriodSeconds)
	}
	if m.addnoise_factor != nil {
		fields = append(fields, sensorsettings.FieldNoiseFactor)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SensorSettingsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case sensorsettings.FieldPollingIntervalSeconds:
		return m.AddedPollingIntervalSeconds()
	case sensorsettings.FieldMinValue:
		return m.AddedMinValue()
	case sensorsettings.FieldMaxValue:
		return m.AddedMaxValue()
	case sensorsettings.FieldMeanValue:
		return m.AddedMeanValue()
	case sensorsettings.FieldStdDeviation:
		return m.AddedStdDeviation()
	case sensorsettings.FieldDriftFactor:
		return m.AddedDriftFactor()
	case sensorsettings.FieldCyclePeriodSeconds:
		return m.AddedCyclePeriodSeconds()
	case sensorsettings.FieldNoiseFactor:
		return m.AddedNoiseFactor()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SensorSettingsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case sensorsettings.FieldPollingIntervalSeconds:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPollingIntervalSeconds(v)
		return nil
	case sensorsettings.FieldMinValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMinValue(v)
		return nil
	case sensorsettings.FieldMaxValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMaxValue(v)
		return nil
	case sensorsettings.FieldMeanValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMeanValue(v)
		return nil
	case sensorsettings.FieldStdDeviation:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStdDeviation(v)
		return nil
	case sensorsettings.FieldDriftFactor:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDriftFactor(v)
		return nil
	case sensorsettings.FieldCyclePeriodSeconds:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCyclePeriodSeconds(v)
		return nil
	case sensorsettings.FieldNoiseFactor:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddNoiseFactor(v)
		return nil
	}
	return fmt.Errorf("unknown SensorSettings numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SensorSettingsMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(sensorsettings.FieldMinValue) {
		fields = append(fields, sensorsettings.FieldMinValue)
	}
	if m.FieldCleared(sensorsettings.FieldMaxValue) {
		fields = append(fields, sensorsettings.FieldMaxValue)
	}
	if m.FieldCleared(sensorsettings.FieldMeanValue) {
		fields = append(fields, sensorsettings.FieldMeanValue)
	}
	if m.FieldCleared(sensorsettings.FieldStdDeviation) {
		fields = append(fields, sensorsettings.FieldStdDeviation)
	}
	if m.FieldCleared(sensorsettings.FieldCyclePeriodSeconds) {
		fields = append(fields, sensorsettings.FieldCyclePeriodSeconds)
	}
	if m.FieldCleared(sensorsettings.FieldPossibleValues) {
		fields = append(fields, sensorsettings.FieldPossibleValues)
	}
	if m.FieldCleared(sensorsettings.FieldAnomalyConfig) {
		fields = append(fields, sensorsettings.FieldAnomalyConfig)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SensorSettingsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SensorSettingsMutation) ClearField(name string) error {
	switch name {
	case sensorsettings.FieldMinValue:
		m.ClearMinValue()
		return nil
	case sensorsettings.FieldMaxValue:
		m.ClearMaxValue()
		return nil
	case sensorsettings.FieldMeanValue:
		m.ClearMeanValue()
		return nil
	case sensorsettings.FieldStdDeviation:
		m.ClearStdDeviation()
		return nil
	case sensorsettings.FieldCyclePeriodSeconds:
		m.ClearCyclePeriodSeconds()
		return nil
	case sensorsettings.FieldPossibleValues:
		m.ClearPossibleValues()
		return nil
	case sensorsettings.FieldAnomalyConfig:
		m.ClearAnomalyConfig()
		return nil
	}
	return fmt.Errorf("unknown SensorSettings nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SensorSettingsMutation) ResetField(name string) error {
	switch name {
	case sensorsettings.FieldPollingIntervalSeconds:
		m.ResetPollingIntervalSeconds()
		return nil
	case sensorsettings.FieldMinValue:
		m.ResetMinValue()
		return nil
	case sensorsettings.FieldMaxValue:
		m.ResetMaxValue()
		return nil
	case sensorsettings.FieldMeanValue:
		m.ResetMeanValue()
		return nil
	case sensorsettings.FieldStdDeviation:
		m.ResetStdDeviation()
		return nil
	case sensorsettings.FieldDriftFactor:
		m.ResetDriftFactor()
		return nil
	case sensorsettings.FieldSeasonalVariation:
		m.ResetSeasonalVariation()
		return nil
	case sensorsettings.FieldCyclePeriodSeconds:
		m.ResetCyclePeriodSeconds()
		return nil
	case sensorsettings.FieldNoiseFactor:
		m.ResetNoiseFactor()
		return nil
	case sensorsettings.FieldPossibleValues:
		m.ResetPossibleValues()
		return nil
	case sensorsettings.FieldAnomalyConfig:
		m.ResetAnomalyConfig()
		return nil
	}
	return fmt.Errorf("unknown SensorSettings field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SensorSettingsMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.sensor_type != nil {
		edges = append(edges, sensorsettings.EdgeSensorType)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SensorSettingsMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case sensorsettings.EdgeSensorType:
		if id := m.sensor_type; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SensorSettingsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SensorSettingsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SensorSettingsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedsensor_type {
		edges = append(edges, sensorsettings.EdgeSensorType)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SensorSettingsMutation) EdgeCleared(name string) bool {
	switch name {
	case sensorsettings.EdgeSensorType:
		return m.clearedsensor_type
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SensorSettingsMutation) ClearEdge(name string) error {
	switch name {
	case sensorsettings.EdgeSensorType:
		m.ClearSensorType()
		return nil
	}
	return fmt.Errorf("unknown SensorSettings unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SensorSettingsMutation) ResetEdge(name string) error {
	switch name {
	case sensorsettings.EdgeSensorType:
		m.ResetSensorType()
		return nil
	}
	return fmt.Errorf("unknown SensorSettings edge %s", name)
}

// SensorTypeMutation represents an operation that mutates the SensorType nodes in the graph.
type SensorTypeMutation struct {
	config
	op              Op
	typ             string
	id              *int
	name            *string
	model           *string
	manufacturer    *string
	description     *string
	clearedFields   map[string]struct{}
	sensors         map[int]struct{}
	removedsensors  map[int]struct{}
	clearedsensors  bool
	settings        *int
	clearedsettings bool
	done            bool
	oldValue        func(context.Context) (*SensorType, error)
	predicates      []predicate.SensorType
}

var _ ent.Mutation = (*SensorTypeMutation)(nil)

// sensortypeOption allows management of the mutation configuration using functional options.
type sensortypeOption func(*SensorTypeMutation)

// newSensorTypeMutation creates new mutation for the SensorType entity.
func newSensorTypeMutation(c config, op Op, opts ...sensortypeOption) *SensorTypeMutation {
	m := &SensorTypeMutation{
		config:        c,
		op:            op,
		typ:           TypeSensorType,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSensorTypeID sets the ID field of the mutation.
func withSensorTypeID(id int) sensortypeOption {
	return func(m *SensorTypeMutation) {
		var (
			err   error
			once  sync.Once
			value *SensorType
		)
		m.oldValue = func(ctx context.Context) (*SensorType, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SensorType.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSensorType sets the old SensorType of the mutation.
func withSensorType(node *SensorType) sensortypeOption {
	return func(m *SensorTypeMutation) {
		m.oldValue = func(context.Context) (*SensorType, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SensorTypeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SensorTypeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SensorTypeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SensorTypeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SensorType.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SensorTypeMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SensorTypeMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the SensorType entity.
// If the SensorType object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorTypeMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SensorTypeMutation) ResetName() {
	m.name = nil
}

// SetModel sets the "model" field.
func (m *SensorTypeMutation) SetModel(s string) {
	m.model = &s
}

// Model returns the value of the "model" field in the mutation.
func (m *SensorTypeMutation) Model() (r string, exists bool) {
	v := m.model
	if v == nil {
		return
	}
	return *v, true
}

// OldModel returns the old "model" field's value of the SensorType entity.
// If the SensorType object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorTypeMutation) OldModel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldModel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldModel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldModel: %w", err)
	}
	return oldValue.Model, nil
}

// ResetModel resets all changes to the "model" field.
func (m *SensorTypeMutation) ResetModel() {
	m.model = nil
}

// SetManufacturer sets the "manufacturer" field.
func (m *SensorTypeMutation) SetManufacturer(s string) {
	m.manufacturer = &s
}

// Manufacturer returns the value of the "manufacturer" field in the mutation.
func (m *SensorTypeMutation) Manufacturer() (r string, exists bool) {
	v := m.manufacturer
	if v == nil {
		return
	}
	return *v, true
}

// OldManufacturer returns the old "manufacturer" field's value of the SensorType entity.
// If the SensorType object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorTypeMutation) OldManufacturer(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldManufacturer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldManufacturer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldManufacturer: %w", err)
	}
	return oldValue.Manufacturer, nil
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (m *SensorTypeMutation) ClearManufacturer() {
	m.manufacturer = nil
	m.clearedFields[sensortype.FieldManufacturer] = struct{}{}
}

// ManufacturerCleared returns if the "manufacturer" field was cleared in this mutation.
func (m *SensorTypeMutation) ManufacturerCleared() bool {
	_, ok := m.clearedFields[sensortype.FieldManufacturer]
	return ok
}

// ResetManufacturer resets all changes to the "manufacturer" field.
func (m *SensorTypeMutation) ResetManufacturer() {
	m.manufacturer = nil
	delete(m.clearedFields, sensortype.FieldManufacturer)
}

// SetDescription sets the "description" field.
func (m *SensorTypeMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *SensorTypeMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the SensorType entity.
// If the SensorType object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SensorTypeMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *SensorTypeMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[sensortype.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *SensorTypeMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[sensortype.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *SensorTypeMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, sensortype.FieldDescription)
}

// AddSensorIDs adds the "sensors" edge to the Sensor entity by ids.
func (m *SensorTypeMutation) AddSensorIDs(ids ...int) {
	if m.sensors == nil {
		m.sensors = make(map[int]struct{})
	}
	for i := range ids {
		m.sensors[ids[i]] = struct{}{}
	}
}

// ClearSensors clears the "sensors" edge to the Sensor entity.
func (m *SensorTypeMutation) ClearSensors() {
	m.clearedsensors = true
}

// SensorsCleared reports if the "sensors" edge to the Sensor entity was cleared.
func (m *SensorTypeMutation) SensorsCleared() bool {
	return m.clearedsensors
}

// RemoveSensorIDs removes the "sensors" edge to the Sensor entity by IDs.
func (m *SensorTypeMutation) RemoveSensorIDs(ids ...int) {
	if m.removedsensors == nil {
		m.removedsensors = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.sensors, ids[i])
		m.removedsensors[ids[i]] = struct{}{}
	}
}

// RemovedSensors returns the removed IDs of the "sensors" edge to the Sensor entity.
func (m *SensorTypeMutation) RemovedSensorsIDs() (ids []int) {
	for id := range m.removedsensors {
		ids = append(ids, id)
	}
	return
}

// SensorsIDs returns the "sensors" edge IDs in the mutation.
func (m *SensorTypeMutation) SensorsIDs() (ids []int) {
	for id := range m.sensors {
		ids = append(ids, id)
	}
	return
}

// ResetSensors resets all changes to the "sensors" edge.
func (m *SensorTypeMutation) ResetSensors() {
	m.sensors = nil
	m.clearedsensors = false
	m.removedsensors = nil
}

// SetSettingsID sets the "settings" edge to the SensorSettings entity by id.
func (m *SensorTypeMutation) SetSettingsID(id int) {
	m.settings = &id
}

// ClearSettings clears the "settings" edge to the SensorSettings entity.
func (m *SensorTypeMutation) ClearSettings() {
	m.clearedsettings = true
}

// SettingsCleared reports if the "settings" edge to the SensorSettings entity was cleared.
func (m *SensorTypeMutation) SettingsCleared() bool {
	return m.clearedsettings
}

// SettingsID returns the "settings" edge ID in the mutation.
func (m *SensorTypeMutation) SettingsID() (id int, exists bool) {
	if m.settings != nil {
		return *m.settings, true
	}
	return
}

// SettingsIDs returns the "settings" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// SettingsID instead. It exists only for internal usage by the builders.
func (m *SensorTypeMutation) SettingsIDs() (ids []int) {
	if id := m.settings; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSettings resets all changes to the "settings" edge.
func (m *SensorTypeMutation) ResetSettings() {
	m.settings = nil
	m.clearedsettings = false
}

// Where appends a list predicates to the SensorTypeMutation builder.
func (m *SensorTypeMutation) Where(ps ...predicate.SensorType) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SensorTypeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SensorTypeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SensorType, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SensorTypeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SensorTypeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SensorType).
func (m *SensorTypeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SensorTypeMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, sensortype.FieldName)
	}
	if m.model != nil {
		fields = append(fields, sensortype.FieldModel)
	}
	if m.manufacturer != nil {
		fields = append(fields, sensortype.FieldManufacturer)
	}
	if m.description != nil {
		fields = append(fields, sensortype.FieldDescription)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SensorTypeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sensortype.FieldName:
		return m.Name()
	case sensortype.FieldModel:
		return m.Model()
	case sensortype.FieldManufacturer:
		return m.Manufacturer()
	case sensortype.FieldDescription:
		return m.Description()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SensorTypeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sensortype.FieldName:
		return m.OldName(ctx)
	case sensortype.FieldModel:
		return m.OldModel(ctx)
	case sensortype.FieldManufacturer:
		return m.OldManufacturer(ctx)
	case sensortype.FieldDescription:
		return m.OldDescription(ctx)
	}
	return nil, fmt.Errorf("unknown SensorType field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SensorTypeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sensortype.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case sensortype.FieldModel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetModel(v)
		return nil
	case sensortype.FieldManufacturer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManufacturer(v)
		return nil
	case sensortype.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	}
	return fmt.Errorf("unknown SensorType field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SensorTypeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SensorTypeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SensorTypeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SensorType numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SensorTypeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(sensortype.FieldManufacturer) {
		fields = append(fields, sensortype.FieldManufacturer)
	}
	if m.FieldCleared(sensortype.FieldDescription) {
		fields = append(fields, sensortype.FieldDescription)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SensorTypeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SensorTypeMutation) ClearField(name string) error {
	switch name {
	case sensortype.FieldManufacturer:
		m.ClearManufacturer()
		return nil
	case sensortype.FieldDescription:
		m.ClearDescription()
		return nil
	}
	return fmt.Errorf("unknown SensorType nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SensorTypeMutation) ResetField(name string) error {
	switch name {
	case sensortype.FieldName:
		m.ResetName()
		return nil
	case sensortype.FieldModel:
		m.ResetModel()
		return nil
	case sensortype.FieldManufacturer:
		m.ResetManufacturer()
		return nil
	case sensortype.FieldDescription:
		m.ResetDescription()
		return nil
	}
	return fmt.Errorf("unknown SensorType field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SensorTypeMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.sensors != nil {
		edges = append(edges, sensortype.EdgeSensors)
	}
	if m.settings != nil {
		edges = append(edges, sensortype.EdgeSettings)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SensorTypeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case sensortype.EdgeSensors:
		ids := make([]ent.Value, 0, len(m.sensors))
		for id := range m.sensors {
			ids = append(ids, id)
		}
		return ids
	case sensortype.EdgeSettings:
		if id := m.settings; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SensorTypeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedsensors != nil {
		edges = append(edges, sensortype.EdgeSensors)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SensorTypeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case sensortype.EdgeSensors:
		ids := make([]ent.Value, 0, len(m.removedsensors))
		for id := range m.removedsensors {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SensorTypeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedsensors {
		edges = append(edges, sensortype.EdgeSensors)
	}
	if m.clearedsettings {
		edges = append(edges, sensortype.EdgeSettings)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SensorTypeMutation) EdgeCleared(name string) bool {
	switch name {
	case sensortype.EdgeSensors:
		return m.clearedsensors
	case sensortype.EdgeSettings:
		return m.clearedsettings
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SensorTypeMutation) ClearEdge(name string) error {
	switch name {
	case sensortype.EdgeSettings:
		m.ClearSettings()
		return nil
	}
	return fmt.Errorf("unknown SensorType unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SensorTypeMutation) ResetEdge(name string) error {
	switch name {
	case sensortype.EdgeSensors:
		m.ResetSensors()
		return nil
	case sensortype.EdgeSettings:
		m.ResetSettings()
		return nil
	}
	return fmt.Errorf("unknown SensorType edge %s", name)
}
