// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/predicate"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensor"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

// SensorTypeQuery is the builder for querying SensorType entities.
type SensorTypeQuery struct {
	config
	ctx          *QueryContext
	order        []sensortype.OrderOption
	inters       []Interceptor
	predicates   []predicate.SensorType
	withSensors  *SensorQuery
	withSettings *SensorSettingsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SensorTypeQuery builder.
func (stq *SensorTypeQuery) Where(ps ...predicate.SensorType) *SensorTypeQuery {
	stq.predicates = append(stq.predicates, ps...)
	return stq
}

// Limit the number of records to be returned by this query.
func (stq *SensorTypeQuery) Limit(limit int) *SensorTypeQuery {
	stq.ctx.Limit = &limit
	return stq
}

// Offset to start from.
func (stq *SensorTypeQuery) Offset(offset int) *SensorTypeQuery {
	stq.ctx.Offset = &offset
	return stq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (stq *SensorTypeQuery) Unique(unique bool) *SensorTypeQuery {
	stq.ctx.Unique = &unique
	return stq
}

// Order specifies how the records should be ordered.
func (stq *SensorTypeQuery) Order(o ...sensortype.OrderOption) *SensorTypeQuery {
	stq.order = append(stq.order, o...)
	return stq
}

// QuerySensors chains the current query on the "sensors" edge.
func (stq *SensorTypeQuery) QuerySensors() *SensorQuery {
	query := (&SensorClient{config: stq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := stq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := stq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sensortype.Table, sensortype.FieldID, selector),
			sqlgraph.To(sensor.Table, sensor.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sensortype.SensorsTable, sensortype.SensorsColumn),
		)
		fromU = sqlgraph.SetNeighbors(stq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySettings chains the current query on the "settings" edge.
func (stq *SensorTypeQuery) QuerySettings() *SensorSettingsQuery {
	query := (&SensorSettingsClient{config: stq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := stq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := stq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sensortype.Table, sensortype.FieldID, selector),
			sqlgraph.To(sensorsettings.Table, sensorsettings.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, sensortype.SettingsTable, sensortype.SettingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(stq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SensorType entity from the query.
// Returns a *NotFoundError when no SensorType was found.
func (stq *SensorTypeQuery) First(ctx context.Context) (*SensorType, error) {
	nodes, err := stq.Limit(1).All(setContextOp(ctx, stq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sensortype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (stq *SensorTypeQuery) FirstX(ctx context.Context) *SensorType {
	node, err := stq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SensorType ID from the query.
// Returns a *NotFoundError when no SensorType ID was found.
func (stq *SensorTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(1).IDs(setContextOp(ctx, stq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sensortype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (stq *SensorTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := stq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SensorType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SensorType entity is found.
// Returns a *NotFoundError when no SensorType entities are found.
func (stq *SensorTypeQuery) Only(ctx context.Context) (*SensorType, error) {
	nodes, err := stq.Limit(2).All(setContextOp(ctx, stq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sensortype.Label}
	default:
		return nil, &NotSingularError{sensortype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (stq *SensorTypeQuery) OnlyX(ctx context.Context) *SensorType {
	node, err := stq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SensorType ID in the query.
// Returns a *NotSingularError when more than one SensorType ID is found.
// Returns a *NotFoundError when no entities are found.
func (stq *SensorTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(2).IDs(setContextOp(ctx, stq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sensortype.Label}
	default:
		err = &NotSingularError{sensortype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (stq *SensorTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := stq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SensorTypes.
func (stq *SensorTypeQuery) All(ctx context.Context) ([]*SensorType, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryAll)
	if err := stq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SensorType, *SensorTypeQuery]()
	return withInterceptors[[]*SensorType](ctx, stq, qr, stq.inters)
}

// AllX is like All, but panics if an error occurs.
func (stq *SensorTypeQuery) AllX(ctx context.Context) []*SensorType {
	nodes, err := stq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SensorType IDs.
func (stq *SensorTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if stq.ctx.Unique == nil && stq.path != nil {
		stq.Unique(true)
	}
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryIDs)
	if err = stq.Select(sensortype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (stq *SensorTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := stq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (stq *SensorTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryCount)
	if err := stq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, stq, querierCount[*SensorTypeQuery](), stq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (stq *SensorTypeQuery) CountX(ctx context.Context) int {
	count, err := stq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (stq *SensorTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryExist)
	switch _, err := stq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (stq *SensorTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := stq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SensorTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (stq *SensorTypeQuery) Clone() *SensorTypeQuery {
	if stq == nil {
		return nil
	}
	return &SensorTypeQuery{
		config:       stq.config,
		ctx:          stq.ctx.Clone(),
		order:        append([]sensortype.OrderOption{}, stq.order...),
		inters:       append([]Interceptor{}, stq.inters...),
		predicates:   append([]predicate.SensorType{}, stq.predicates...),
		withSensors:  stq.withSensors.Clone(),
		withSettings: stq.withSettings.Clone(),
		// clone intermediate query.
		sql:  stq.sql.Clone(),
		path: stq.path,
	}
}

// WithSensors tells the query-builder to eager-load the nodes that are connected to
// the "sensors" edge. The optional arguments are used to configure the query builder of the edge.
func (stq *SensorTypeQuery) WithSensors(opts ...func(*SensorQuery)) *SensorTypeQuery {
	query := (&SensorClient{config: stq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	stq.withSensors = query
	return stq
}

// WithSettings tells the query-builder to eager-load the nodes that are connected to
// the "settings" edge. The optional arguments are used to configure the query builder of the edge.
func (stq *SensorTypeQuery) WithSettings(opts ...func(*SensorSettingsQuery)) *SensorTypeQuery {
	query := (&SensorSettingsClient{config: stq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	stq.withSettings = query
	return stq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SensorType.Query().
//		GroupBy(sensortype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (stq *SensorTypeQuery) GroupBy(field string, fields ...string) *SensorTypeGroupBy {
	stq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SensorTypeGroupBy{build: stq}
	grbuild.flds = &stq.ctx.Fields
	grbuild.label = sensortype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.SensorType.Query().
//		Select(sensortype.FieldName).
//		Scan(ctx, &v)
func (stq *SensorTypeQuery) Select(fields ...string) *SensorTypeSelect {
	stq.ctx.Fields = append(stq.ctx.Fields, fields...)
	sbuild := &SensorTypeSelect{SensorTypeQuery: stq}
	sbuild.label = sensortype.Label
	sbuild.flds, sbuild.scan = &stq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SensorTypeSelect configured with the given aggregations.
func (stq *SensorTypeQuery) Aggregate(fns ...AggregateFunc) *SensorTypeSelect {
	return stq.Select().Aggregate(fns...)
}

func (stq *SensorTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range stq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, stq); err != nil {
				return err
			}
		}
	}
	for _, f := range stq.ctx.Fields {
		if !sensortype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if stq.path != nil {
		prev, err := stq.path(ctx)
		if err != nil {
			return err
		}
		stq.sql = prev
	}
	return nil
}

func (stq *SensorTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SensorType, error) {
	var (
		nodes       = []*SensorType{}
		_spec       = stq.querySpec()
		loadedTypes = [2]bool{
			stq.withSensors != nil,
			stq.withSettings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SensorType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SensorType{config: stq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, stq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := stq.withSensors; query != nil {
		if err := stq.loadSensors(ctx, query, nodes,
			func(n *SensorType) { n.Edges.Sensors = []*Sensor{} },
			func(n *SensorType, e *Sensor) { n.Edges.Sensors = append(n.Edges.Sensors, e) }); err != nil {
			return nil, err
		}
	}
	if query := stq.withSettings; query != nil {
		if err := stq.loadSettings(ctx, query, nodes, nil,
			func(n *SensorType, e *SensorSettings) { n.Edges.Settings = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (stq *SensorTypeQuery) loadSensors(ctx context.Context, query *SensorQuery, nodes []*SensorType, init func(*SensorType), assign func(*SensorType, *Sensor)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SensorType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Sensor(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(sensortype.SensorsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sensor_type
		if fk == nil {
			return fmt.Errorf(`foreign-key "sensor_type" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sensor_type" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (stq *SensorTypeQuery) loadSettings(ctx context.Context, query *SensorSettingsQuery, nodes []*SensorType, init func(*SensorType), assign func(*SensorType, *SensorSettings)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SensorType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.SensorSettings(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(sensortype.SettingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sensor_type_settings
		if fk == nil {
			return fmt.Errorf(`foreign-key "sensor_type_settings" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sensor_type_settings" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (stq *SensorTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := stq.querySpec()
	_spec.Node.Columns = stq.ctx.Fields
	if len(stq.ctx.Fields) > 0 {
		_spec.Unique = stq.ctx.Unique != nil && *stq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, stq.driver, _spec)
}

func (stq *SensorTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sensortype.Table, sensortype.Columns, sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt))
	_spec.From = stq.sql
	if unique := stq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if stq.path != nil {
		_spec.Unique = true
	}
	if fields := stq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sensortype.FieldID)
		for i := range fields {
			if fields[i] != sensortype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := stq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := stq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := stq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := stq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (stq *SensorTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(stq.driver.Dialect())
	t1 := builder.Table(sensortype.Table)
	columns := stq.ctx.Fields
	if len(columns) == 0 {
		columns = sensortype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if stq.sql != nil {
		selector = stq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if stq.ctx.Unique != nil && *stq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range stq.predicates {
		p(selector)
	}
	for _, p := range stq.order {
		p(selector)
	}
	if offset := stq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := stq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SensorTypeGroupBy is the group-by builder for SensorType entities.
type SensorTypeGroupBy struct {
	selector
	build *SensorTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (stgb *SensorTypeGroupBy) Aggregate(fns ...AggregateFunc) *SensorTypeGroupBy {
	stgb.fns = append(stgb.fns, fns...)
	return stgb
}

// Scan applies the selector query and scans the result into the given value.
func (stgb *SensorTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stgb.build.ctx, ent.OpQueryGroupBy)
	if err := stgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SensorTypeQuery, *SensorTypeGroupBy](ctx, stgb.build, stgb, stgb.build.inters, v)
}

func (stgb *SensorTypeGroupBy) sqlScan(ctx context.Context, root *SensorTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(stgb.fns))
	for _, fn := range stgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*stgb.flds)+len(stgb.fns))
		for _, f := range *stgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*stgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := stgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SensorTypeSelect is the builder for selecting fields of SensorType entities.
type SensorTypeSelect struct {
	*SensorTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sts *SensorTypeSelect) Aggregate(fns ...AggregateFunc) *SensorTypeSelect {
	sts.fns = append(sts.fns, fns...)
	return sts
}

// Scan applies the selector query and scans the result into the given value.
func (sts *SensorTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sts.ctx, ent.OpQuerySelect)
	if err := sts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SensorTypeQuery, *SensorTypeSelect](ctx, sts.SensorTypeQuery, sts, sts.inters, v)
}

func (sts *SensorTypeSelect) sqlScan(ctx context.Context, root *SensorTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sts.fns))
	for _, fn := range sts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
