// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/predicate"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

// SensorSettingsQuery is the builder for querying SensorSettings entities.
type SensorSettingsQuery struct {
	config
	ctx            *QueryContext
	order          []sensorsettings.OrderOption
	inters         []Interceptor
	predicates     []predicate.SensorSettings
	withSensorType *SensorTypeQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SensorSettingsQuery builder.
func (ssq *SensorSettingsQuery) Where(ps ...predicate.SensorSettings) *SensorSettingsQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *SensorSettingsQuery) Limit(limit int) *SensorSettingsQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *SensorSettingsQuery) Offset(offset int) *SensorSettingsQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *SensorSettingsQuery) Unique(unique bool) *SensorSettingsQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *SensorSettingsQuery) Order(o ...sensorsettings.OrderOption) *SensorSettingsQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// QuerySensorType chains the current query on the "sensor_type" edge.
func (ssq *SensorSettingsQuery) QuerySensorType() *SensorTypeQuery {
	query := (&SensorTypeClient{config: ssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sensorsettings.Table, sensorsettings.FieldID, selector),
			sqlgraph.To(sensortype.Table, sensortype.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, sensorsettings.SensorTypeTable, sensorsettings.SensorTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(ssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SensorSettings entity from the query.
// Returns a *NotFoundError when no SensorSettings was found.
func (ssq *SensorSettingsQuery) First(ctx context.Context) (*SensorSettings, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sensorsettings.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *SensorSettingsQuery) FirstX(ctx context.Context) *SensorSettings {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SensorSettings ID from the query.
// Returns a *NotFoundError when no SensorSettings ID was found.
func (ssq *SensorSettingsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sensorsettings.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *SensorSettingsQuery) FirstIDX(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SensorSettings entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SensorSettings entity is found.
// Returns a *NotFoundError when no SensorSettings entities are found.
func (ssq *SensorSettingsQuery) Only(ctx context.Context) (*SensorSettings, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sensorsettings.Label}
	default:
		return nil, &NotSingularError{sensorsettings.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *SensorSettingsQuery) OnlyX(ctx context.Context) *SensorSettings {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SensorSettings ID in the query.
// Returns a *NotSingularError when more than one SensorSettings ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *SensorSettingsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sensorsettings.Label}
	default:
		err = &NotSingularError{sensorsettings.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *SensorSettingsQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SensorSettingsSlice.
func (ssq *SensorSettingsQuery) All(ctx context.Context) ([]*SensorSettings, error) {
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryAll)
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SensorSettings, *SensorSettingsQuery]()
	return withInterceptors[[]*SensorSettings](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *SensorSettingsQuery) AllX(ctx context.Context) []*SensorSettings {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SensorSettings IDs.
func (ssq *SensorSettingsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ssq.ctx.Unique == nil && ssq.path != nil {
		ssq.Unique(true)
	}
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryIDs)
	if err = ssq.Select(sensorsettings.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *SensorSettingsQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *SensorSettingsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryCount)
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*SensorSettingsQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *SensorSettingsQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *SensorSettingsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, ent.OpQueryExist)
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *SensorSettingsQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SensorSettingsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *SensorSettingsQuery) Clone() *SensorSettingsQuery {
	if ssq == nil {
		return nil
	}
	return &SensorSettingsQuery{
		config:         ssq.config,
		ctx:            ssq.ctx.Clone(),
		order:          append([]sensorsettings.OrderOption{}, ssq.order...),
		inters:         append([]Interceptor{}, ssq.inters...),
		predicates:     append([]predicate.SensorSettings{}, ssq.predicates...),
		withSensorType: ssq.withSensorType.Clone(),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// WithSensorType tells the query-builder to eager-load the nodes that are connected to
// the "sensor_type" edge. The optional arguments are used to configure the query builder of the edge.
func (ssq *SensorSettingsQuery) WithSensorType(opts ...func(*SensorTypeQuery)) *SensorSettingsQuery {
	query := (&SensorTypeClient{config: ssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ssq.withSensorType = query
	return ssq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PollingIntervalSeconds int `json:"polling_interval_seconds,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SensorSettings.Query().
//		GroupBy(sensorsettings.FieldPollingIntervalSeconds).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ssq *SensorSettingsQuery) GroupBy(field string, fields ...string) *SensorSettingsGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SensorSettingsGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = sensorsettings.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PollingIntervalSeconds int `json:"polling_interval_seconds,omitempty"`
//	}
//
//	client.SensorSettings.Query().
//		Select(sensorsettings.FieldPollingIntervalSeconds).
//		Scan(ctx, &v)
func (ssq *SensorSettingsQuery) Select(fields ...string) *SensorSettingsSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &SensorSettingsSelect{SensorSettingsQuery: ssq}
	sbuild.label = sensorsettings.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SensorSettingsSelect configured with the given aggregations.
func (ssq *SensorSettingsQuery) Aggregate(fns ...AggregateFunc) *SensorSettingsSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *SensorSettingsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !sensorsettings.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *SensorSettingsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SensorSettings, error) {
	var (
		nodes       = []*SensorSettings{}
		withFKs     = ssq.withFKs
		_spec       = ssq.querySpec()
		loadedTypes = [1]bool{
			ssq.withSensorType != nil,
		}
	)
	if ssq.withSensorType != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, sensorsettings.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SensorSettings).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SensorSettings{config: ssq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ssq.withSensorType; query != nil {
		if err := ssq.loadSensorType(ctx, query, nodes, nil,
			func(n *SensorSettings, e *SensorType) { n.Edges.SensorType = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ssq *SensorSettingsQuery) loadSensorType(ctx context.Context, query *SensorTypeQuery, nodes []*SensorSettings, init func(*SensorSettings), assign func(*SensorSettings, *SensorType)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SensorSettings)
	for i := range nodes {
		if nodes[i].sensor_type_settings == nil {
			continue
		}
		fk := *nodes[i].sensor_type_settings
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sensortype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sensor_type_settings" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ssq *SensorSettingsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *SensorSettingsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sensorsettings.Table, sensorsettings.Columns, sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt))
	_spec.From = ssq.sql
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssq.path != nil {
		_spec.Unique = true
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sensorsettings.FieldID)
		for i := range fields {
			if fields[i] != sensorsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *SensorSettingsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(sensorsettings.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = sensorsettings.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SensorSettingsGroupBy is the group-by builder for SensorSettings entities.
type SensorSettingsGroupBy struct {
	selector
	build *SensorSettingsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *SensorSettingsGroupBy) Aggregate(fns ...AggregateFunc) *SensorSettingsGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *SensorSettingsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, ent.OpQueryGroupBy)
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SensorSettingsQuery, *SensorSettingsGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *SensorSettingsGroupBy) sqlScan(ctx context.Context, root *SensorSettingsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SensorSettingsSelect is the builder for selecting fields of SensorSettings entities.
type SensorSettingsSelect struct {
	*SensorSettingsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *SensorSettingsSelect) Aggregate(fns ...AggregateFunc) *SensorSettingsSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *SensorSettingsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, ent.OpQuerySelect)
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SensorSettingsQuery, *SensorSettingsSelect](ctx, sss.SensorSettingsQuery, sss, sss.inters, v)
}

func (sss *SensorSettingsSelect) sqlScan(ctx context.Context, root *SensorSettingsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
