// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

// SensorSettingsCreate is the builder for creating a SensorSettings entity.
type SensorSettingsCreate struct {
	config
	mutation *SensorSettingsMutation
	hooks    []Hook
}

// SetPollingIntervalSeconds sets the "polling_interval_seconds" field.
func (ssc *SensorSettingsCreate) SetPollingIntervalSeconds(i int) *SensorSettingsCreate {
	ssc.mutation.SetPollingIntervalSeconds(i)
	return ssc
}

// SetNillablePollingIntervalSeconds sets the "polling_interval_seconds" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillablePollingIntervalSeconds(i *int) *SensorSettingsCreate {
	if i != nil {
		ssc.SetPollingIntervalSeconds(*i)
	}
	return ssc
}

// SetMinValue sets the "min_value" field.
func (ssc *SensorSettingsCreate) SetMinValue(f float64) *SensorSettingsCreate {
	ssc.mutation.SetMinValue(f)
	return ssc
}

// SetNillableMinValue sets the "min_value" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableMinValue(f *float64) *SensorSettingsCreate {
	if f != nil {
		ssc.SetMinValue(*f)
	}
	return ssc
}

// SetMaxValue sets the "max_value" field.
func (ssc *SensorSettingsCreate) SetMaxValue(f float64) *SensorSettingsCreate {
	ssc.mutation.SetMaxValue(f)
	return ssc
}

// SetNillableMaxValue sets the "max_value" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableMaxValue(f *float64) *SensorSettingsCreate {
	if f != nil {
		ssc.SetMaxValue(*f)
	}
	return ssc
}

// SetMeanValue sets the "mean_value" field.
func (ssc *SensorSettingsCreate) SetMeanValue(f float64) *SensorSettingsCreate {
	ssc.mutation.SetMeanValue(f)
	return ssc
}

// SetNillableMeanValue sets the "mean_value" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableMeanValue(f *float64) *SensorSettingsCreate {
	if f != nil {
		ssc.SetMeanValue(*f)
	}
	return ssc
}

// SetStdDeviation sets the "std_deviation" field.
func (ssc *SensorSettingsCreate) SetStdDeviation(f float64) *SensorSettingsCreate {
	ssc.mutation.SetStdDeviation(f)
	return ssc
}

// SetNillableStdDeviation sets the "std_deviation" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableStdDeviation(f *float64) *SensorSettingsCreate {
	if f != nil {
		ssc.SetStdDeviation(*f)
	}
	return ssc
}

// SetDriftFactor sets the "drift_factor" field.
func (ssc *SensorSettingsCreate) SetDriftFactor(f float64) *SensorSettingsCreate {
	ssc.mutation.SetDriftFactor(f)
	return ssc
}

// SetNillableDriftFactor sets the "drift_factor" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableDriftFactor(f *float64) *SensorSettingsCreate {
	if f != nil {
		ssc.SetDriftFactor(*f)
	}
	return ssc
}

// SetSeasonalVariation sets the "seasonal_variation" field.
func (ssc *SensorSettingsCreate) SetSeasonalVariation(b bool) *SensorSettingsCreate {
	ssc.mutation.SetSeasonalVariation(b)
	return ssc
}

// SetNillableSeasonalVariation sets the "seasonal_variation" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableSeasonalVariation(b *bool) *SensorSettingsCreate {
	if b != nil {
		ssc.SetSeasonalVariation(*b)
	}
	return ssc
}

// SetCyclePeriodSeconds sets the "cycle_period_seconds" field.
func (ssc *SensorSettingsCreate) SetCyclePeriodSeconds(i int) *SensorSettingsCreate {
	ssc.mutation.SetCyclePeriodSeconds(i)
	return ssc
}

// SetNillableCyclePeriodSeconds sets the "cycle_period_seconds" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableCyclePeriodSeconds(i *int) *SensorSettingsCreate {
	if i != nil {
		ssc.SetCyclePeriodSeconds(*i)
	}
	return ssc
}

// SetNoiseFactor sets the "noise_factor" field.
func (ssc *SensorSettingsCreate) SetNoiseFactor(f float64) *SensorSettingsCreate {
	ssc.mutation.SetNoiseFactor(f)
	return ssc
}

// SetNillableNoiseFactor sets the "noise_factor" field if the given value is not nil.
func (ssc *SensorSettingsCreate) SetNillableNoiseFactor(f *float64) *SensorSettingsCreate {
	if f != nil {
		ssc.SetNoiseFactor(*f)
	}
	return ssc
}

// SetPossibleValues sets the "possible_values" field.
func (ssc *SensorSettingsCreate) SetPossibleValues(s []string) *SensorSettingsCreate {
	ssc.mutation.SetPossibleValues(s)
	return ssc
}

// SetAnomalyConfig sets the "anomaly_config" field.
func (ssc *SensorSettingsCreate) SetAnomalyConfig(m map[string]interface{}) *SensorSettingsCreate {
	ssc.mutation.SetAnomalyConfig(m)
	return ssc
}

// SetSensorTypeID sets the "sensor_type" edge to the SensorType entity by ID.
func (ssc *SensorSettingsCreate) SetSensorTypeID(id int) *SensorSettingsCreate {
	ssc.mutation.SetSensorTypeID(id)
	return ssc
}

// SetSensorType sets the "sensor_type" edge to the SensorType entity.
func (ssc *SensorSettingsCreate) SetSensorType(s *SensorType) *SensorSettingsCreate {
	return ssc.SetSensorTypeID(s.ID)
}

// Mutation returns the SensorSettingsMutation object of the builder.
func (ssc *SensorSettingsCreate) Mutation() *SensorSettingsMutation {
	return ssc.mutation
}

// Save creates the SensorSettings in the database.
func (ssc *SensorSettingsCreate) Save(ctx context.Context) (*SensorSettings, error) {
	ssc.defaults()
	return withHooks(ctx, ssc.sqlSave, ssc.mutation, ssc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ssc *SensorSettingsCreate) SaveX(ctx context.Context) *SensorSettings {
	v, err := ssc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssc *SensorSettingsCreate) Exec(ctx context.Context) error {
	_, err := ssc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssc *SensorSettingsCreate) ExecX(ctx context.Context) {
	if err := ssc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssc *SensorSettingsCreate) defaults() {
	if _, ok := ssc.mutation.PollingIntervalSeconds(); !ok {
		v := sensorsettings.DefaultPollingIntervalSeconds
		ssc.mutation.SetPollingIntervalSeconds(v)
	}
	if _, ok := ssc.mutation.DriftFactor(); !ok {
		v := sensorsettings.DefaultDriftFactor
		ssc.mutation.SetDriftFactor(v)
	}
	if _, ok := ssc.mutation.SeasonalVariation(); !ok {
		v := sensorsettings.DefaultSeasonalVariation
		ssc.mutation.SetSeasonalVariation(v)
	}
	if _, ok := ssc.mutation.NoiseFactor(); !ok {
		v := sensorsettings.DefaultNoiseFactor
		ssc.mutation.SetNoiseFactor(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssc *SensorSettingsCreate) check() error {
	if _, ok := ssc.mutation.PollingIntervalSeconds(); !ok {
		return &ValidationError{Name: "polling_interval_seconds", err: errors.New(`ent: missing required field "SensorSettings.polling_interval_seconds"`)}
	}
	if v, ok := ssc.mutation.PollingIntervalSeconds(); ok {
		if err := sensorsettings.PollingIntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "polling_interval_seconds", err: fmt.Errorf(`ent: validator failed for field "SensorSettings.polling_interval_seconds": %w`, err)}
		}
	}
	if _, ok := ssc.mutation.DriftFactor(); !ok {
		return &ValidationError{Name: "drift_factor", err: errors.New(`ent: missing required field "SensorSettings.drift_factor"`)}
	}
	if _, ok := ssc.mutation.SeasonalVariation(); !ok {
		return &ValidationError{Name: "seasonal_variation", err: errors.New(`ent: missing required field "SensorSettings.seasonal_variation"`)}
	}
	if _, ok := ssc.mutation.NoiseFactor(); !ok {
		return &ValidationError{Name: "noise_factor", err: errors.New(`ent: missing required field "SensorSettings.noise_factor"`)}
	}
	if len(ssc.mutation.SensorTypeIDs()) == 0 {
		return &ValidationError{Name: "sensor_type", err: errors.New(`ent: missing required edge "SensorSettings.sensor_type"`)}
	}
	return nil
}

func (ssc *SensorSettingsCreate) sqlSave(ctx context.Context) (*SensorSettings, error) {
	if err := ssc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ssc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ssc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ssc.mutation.id = &_node.ID
	ssc.mutation.done = true
	return _node, nil
}

func (ssc *SensorSettingsCreate) createSpec() (*SensorSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &SensorSettings{config: ssc.config}
		_spec = sqlgraph.NewCreateSpec(sensorsettings.Table, sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt))
	)
	if value, ok := ssc.mutation.PollingIntervalSeconds(); ok {
		_spec.SetField(sensorsettings.FieldPollingIntervalSeconds, field.TypeInt, value)
		_node.PollingIntervalSeconds = value
	}
	if value, ok := ssc.mutation.MinValue(); ok {
		_spec.SetField(sensorsettings.FieldMinValue, field.TypeFloat64, value)
		_node.MinValue = value
	}
	if value, ok := ssc.mutation.MaxValue(); ok {
		_spec.SetField(sensorsettings.FieldMaxValue, field.TypeFloat64, value)
		_node.MaxValue = value
	}
	if value, ok := ssc.mutation.MeanValue(); ok {
		_spec.SetField(sensorsettings.FieldMeanValue, field.TypeFloat64, value)
		_node.MeanValue = value
	}
	if value, ok := ssc.mutation.StdDeviation(); ok {
		_spec.SetField(sensorsettings.FieldStdDeviation, field.TypeFloat64, value)
		_node.StdDeviation = value
	}
	if value, ok := ssc.mutation.DriftFactor(); ok {
		_spec.SetField(sensorsettings.FieldDriftFactor, field.TypeFloat64, value)
		_node.DriftFactor = value
	}
	if value, ok := ssc.mutation.SeasonalVariation(); ok {
		_spec.SetField(sensorsettings.FieldSeasonalVariation, field.TypeBool, value)
		_node.SeasonalVariation = value
	}
	if value, ok := ssc.mutation.CyclePeriodSeconds(); ok {
		_spec.SetField(sensorsettings.FieldCyclePeriodSeconds, field.TypeInt, value)
		_node.CyclePeriodSeconds = value
	}
	if value, ok := ssc.mutation.NoiseFactor(); ok {
		_spec.SetField(sensorsettings.FieldNoiseFactor, field.TypeFloat64, value)
		_node.NoiseFactor = value
	}
	if value, ok := ssc.mutation.PossibleValues(); ok {
		_spec.SetField(sensorsettings.FieldPossibleValues, field.TypeJSON, value)
		_node.PossibleValues = value
	}
	if value, ok := ssc.mutation.AnomalyConfig(); ok {
		_spec.SetField(sensorsettings.FieldAnomalyConfig, field.TypeJSON, value)
		_node.AnomalyConfig = value
	}
	if nodes := ssc.mutation.SensorTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sensorsettings.SensorTypeTable,
			Columns: []string{sensorsettings.SensorTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sensor_type_settings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SensorSettingsCreateBulk is the builder for creating many SensorSettings entities in bulk.
type SensorSettingsCreateBulk struct {
	config
	err      error
	builders []*SensorSettingsCreate
}

// Save creates the SensorSettings entities in the database.
func (sscb *SensorSettingsCreateBulk) Save(ctx context.Context) ([]*SensorSettings, error) {
	if sscb.err != nil {
		return nil, sscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sscb.builders))
	nodes := make([]*SensorSettings, len(sscb.builders))
	mutators := make([]Mutator, len(sscb.builders))
	for i := range sscb.builders {
		func(i int, root context.Context) {
			builder := sscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SensorSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sscb *SensorSettingsCreateBulk) SaveX(ctx context.Context) []*SensorSettings {
	v, err := sscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sscb *SensorSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := sscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sscb *SensorSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := sscb.Exec(ctx); err != nil {
		panic(err)
	}
}
