// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

// SensorSettings is the model entity for the SensorSettings schema.
type SensorSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// How often the simulated sensor should generate new data
	PollingIntervalSeconds int `json:"polling_interval_seconds,omitempty"`
	// Minimum possible value for this sensor type (for simulation)
	MinValue float64 `json:"min_value,omitempty"`
	// Maximum possible value for this sensor type (for simulation)
	MaxValue float64 `json:"max_value,omitempty"`
	// Mean value for normal distribution in simulation
	MeanValue float64 `json:"mean_value,omitempty"`
	// Standard deviation for normal distribution in simulation
	StdDeviation float64 `json:"std_deviation,omitempty"`
	// Gradual drift to apply to values over time
	DriftFactor float64 `json:"drift_factor,omitempty"`
	// Whether to apply seasonal/cyclic variations
	SeasonalVariation bool `json:"seasonal_variation,omitempty"`
	// Period of cyclic variation in seconds
	CyclePeriodSeconds int `json:"cycle_period_seconds,omitempty"`
	// Amount of random noise to add to readings (0-1)
	NoiseFactor float64 `json:"noise_factor,omitempty"`
	// Possible values for categorical sensors
	PossibleValues []string `json:"possible_values,omitempty"`
	// Configuration for simulating anomalies
	AnomalyConfig map[string]interface{} `json:"anomaly_config,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SensorSettingsQuery when eager-loading is set.
	Edges                SensorSettingsEdges `json:"edges"`
	sensor_type_settings *int
	selectValues         sql.SelectValues
}

// SensorSettingsEdges holds the relations/edges for other nodes in the graph.
type SensorSettingsEdges struct {
	// The sensor type these settings apply to
	SensorType *SensorType `json:"sensor_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SensorTypeOrErr returns the SensorType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SensorSettingsEdges) SensorTypeOrErr() (*SensorType, error) {
	if e.SensorType != nil {
		return e.SensorType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sensortype.Label}
	}
	return nil, &NotLoadedError{edge: "sensor_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SensorSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sensorsettings.FieldPossibleValues, sensorsettings.FieldAnomalyConfig:
			values[i] = new([]byte)
		case sensorsettings.FieldSeasonalVariation:
			values[i] = new(sql.NullBool)
		case sensorsettings.FieldMinValue, sensorsettings.FieldMaxValue, sensorsettings.FieldMeanValue, sensorsettings.FieldStdDeviation, sensorsettings.FieldDriftFactor, sensorsettings.FieldNoiseFactor:
			values[i] = new(sql.NullFloat64)
		case sensorsettings.FieldID, sensorsettings.FieldPollingIntervalSeconds, sensorsettings.FieldCyclePeriodSeconds:
			values[i] = new(sql.NullInt64)
		case sensorsettings.ForeignKeys[0]: // sensor_type_settings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SensorSettings fields.
func (ss *SensorSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sensorsettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ss.ID = int(value.Int64)
		case sensorsettings.FieldPollingIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field polling_interval_seconds", values[i])
			} else if value.Valid {
				ss.PollingIntervalSeconds = int(value.Int64)
			}
		case sensorsettings.FieldMinValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field min_value", values[i])
			} else if value.Valid {
				ss.MinValue = value.Float64
			}
		case sensorsettings.FieldMaxValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field max_value", values[i])
			} else if value.Valid {
				ss.MaxValue = value.Float64
			}
		case sensorsettings.FieldMeanValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field mean_value", values[i])
			} else if value.Valid {
				ss.MeanValue = value.Float64
			}
		case sensorsettings.FieldStdDeviation:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field std_deviation", values[i])
			} else if value.Valid {
				ss.StdDeviation = value.Float64
			}
		case sensorsettings.FieldDriftFactor:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field drift_factor", values[i])
			} else if value.Valid {
				ss.DriftFactor = value.Float64
			}
		case sensorsettings.FieldSeasonalVariation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field seasonal_variation", values[i])
			} else if value.Valid {
				ss.SeasonalVariation = value.Bool
			}
		case sensorsettings.FieldCyclePeriodSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_period_seconds", values[i])
			} else if value.Valid {
				ss.CyclePeriodSeconds = int(value.Int64)
			}
		case sensorsettings.FieldNoiseFactor:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field noise_factor", values[i])
			} else if value.Valid {
				ss.NoiseFactor = value.Float64
			}
		case sensorsettings.FieldPossibleValues:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field possible_values", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ss.PossibleValues); err != nil {
					return fmt.Errorf("unmarshal field possible_values: %w", err)
				}
			}
		case sensorsettings.FieldAnomalyConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field anomaly_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ss.AnomalyConfig); err != nil {
					return fmt.Errorf("unmarshal field anomaly_config: %w", err)
				}
			}
		case sensorsettings.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sensor_type_settings", value)
			} else if value.Valid {
				ss.sensor_type_settings = new(int)
				*ss.sensor_type_settings = int(value.Int64)
			}
		default:
			ss.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SensorSettings.
// This includes values selected through modifiers, order, etc.
func (ss *SensorSettings) Value(name string) (ent.Value, error) {
	return ss.selectValues.Get(name)
}

// QuerySensorType queries the "sensor_type" edge of the SensorSettings entity.
func (ss *SensorSettings) QuerySensorType() *SensorTypeQuery {
	return NewSensorSettingsClient(ss.config).QuerySensorType(ss)
}

// Update returns a builder for updating this SensorSettings.
// Note that you need to call SensorSettings.Unwrap() before calling this method if this SensorSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (ss *SensorSettings) Update() *SensorSettingsUpdateOne {
	return NewSensorSettingsClient(ss.config).UpdateOne(ss)
}

// Unwrap unwraps the SensorSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ss *SensorSettings) Unwrap() *SensorSettings {
	_tx, ok := ss.config.driver.(*txDriver)
	if !ok {
		panic("ent: SensorSettings is not a transactional entity")
	}
	ss.config.driver = _tx.drv
	return ss
}

// String implements the fmt.Stringer.
func (ss *SensorSettings) String() string {
	var builder strings.Builder
	builder.WriteString("SensorSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ss.ID))
	builder.WriteString("polling_interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", ss.PollingIntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("min_value=")
	builder.WriteString(fmt.Sprintf("%v", ss.MinValue))
	builder.WriteString(", ")
	builder.WriteString("max_value=")
	builder.WriteString(fmt.Sprintf("%v", ss.MaxValue))
	builder.WriteString(", ")
	builder.WriteString("mean_value=")
	builder.WriteString(fmt.Sprintf("%v", ss.MeanValue))
	builder.WriteString(", ")
	builder.WriteString("std_deviation=")
	builder.WriteString(fmt.Sprintf("%v", ss.StdDeviation))
	builder.WriteString(", ")
	builder.WriteString("drift_factor=")
	builder.WriteString(fmt.Sprintf("%v", ss.DriftFactor))
	builder.WriteString(", ")
	builder.WriteString("seasonal_variation=")
	builder.WriteString(fmt.Sprintf("%v", ss.SeasonalVariation))
	builder.WriteString(", ")
	builder.WriteString("cycle_period_seconds=")
	builder.WriteString(fmt.Sprintf("%v", ss.CyclePeriodSeconds))
	builder.WriteString(", ")
	builder.WriteString("noise_factor=")
	builder.WriteString(fmt.Sprintf("%v", ss.NoiseFactor))
	builder.WriteString(", ")
	builder.WriteString("possible_values=")
	builder.WriteString(fmt.Sprintf("%v", ss.PossibleValues))
	builder.WriteString(", ")
	builder.WriteString("anomaly_config=")
	builder.WriteString(fmt.Sprintf("%v", ss.AnomalyConfig))
	builder.WriteByte(')')
	return builder.String()
}

// SensorSettingsSlice is a parsable slice of SensorSettings.
type SensorSettingsSlice []*SensorSettings
