// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/predicate"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensor"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

// SensorTypeUpdate is the builder for updating SensorType entities.
type SensorTypeUpdate struct {
	config
	hooks    []Hook
	mutation *SensorTypeMutation
}

// Where appends a list predicates to the SensorTypeUpdate builder.
func (stu *SensorTypeUpdate) Where(ps ...predicate.SensorType) *SensorTypeUpdate {
	stu.mutation.Where(ps...)
	return stu
}

// SetName sets the "name" field.
func (stu *SensorTypeUpdate) SetName(s string) *SensorTypeUpdate {
	stu.mutation.SetName(s)
	return stu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (stu *SensorTypeUpdate) SetNillableName(s *string) *SensorTypeUpdate {
	if s != nil {
		stu.SetName(*s)
	}
	return stu
}

// SetModel sets the "model" field.
func (stu *SensorTypeUpdate) SetModel(s string) *SensorTypeUpdate {
	stu.mutation.SetModel(s)
	return stu
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (stu *SensorTypeUpdate) SetNillableModel(s *string) *SensorTypeUpdate {
	if s != nil {
		stu.SetModel(*s)
	}
	return stu
}

// SetManufacturer sets the "manufacturer" field.
func (stu *SensorTypeUpdate) SetManufacturer(s string) *SensorTypeUpdate {
	stu.mutation.SetManufacturer(s)
	return stu
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (stu *SensorTypeUpdate) SetNillableManufacturer(s *string) *SensorTypeUpdate {
	if s != nil {
		stu.SetManufacturer(*s)
	}
	return stu
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (stu *SensorTypeUpdate) ClearManufacturer() *SensorTypeUpdate {
	stu.mutation.ClearManufacturer()
	return stu
}

// SetDescription sets the "description" field.
func (stu *SensorTypeUpdate) SetDescription(s string) *SensorTypeUpdate {
	stu.mutation.SetDescription(s)
	return stu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (stu *SensorTypeUpdate) SetNillableDescription(s *string) *SensorTypeUpdate {
	if s != nil {
		stu.SetDescription(*s)
	}
	return stu
}

// ClearDescription clears the value of the "description" field.
func (stu *SensorTypeUpdate) ClearDescription() *SensorTypeUpdate {
	stu.mutation.ClearDescription()
	return stu
}

// AddSensorIDs adds the "sensors" edge to the Sensor entity by IDs.
func (stu *SensorTypeUpdate) AddSensorIDs(ids ...int) *SensorTypeUpdate {
	stu.mutation.AddSensorIDs(ids...)
	return stu
}

// AddSensors adds the "sensors" edges to the Sensor entity.
func (stu *SensorTypeUpdate) AddSensors(s ...*Sensor) *SensorTypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return stu.AddSensorIDs(ids...)
}

// SetSettingsID sets the "settings" edge to the SensorSettings entity by ID.
func (stu *SensorTypeUpdate) SetSettingsID(id int) *SensorTypeUpdate {
	stu.mutation.SetSettingsID(id)
	return stu
}

// SetNillableSettingsID sets the "settings" edge to the SensorSettings entity by ID if the given value is not nil.
func (stu *SensorTypeUpdate) SetNillableSettingsID(id *int) *SensorTypeUpdate {
	if id != nil {
		stu = stu.SetSettingsID(*id)
	}
	return stu
}

// SetSettings sets the "settings" edge to the SensorSettings entity.
func (stu *SensorTypeUpdate) SetSettings(s *SensorSettings) *SensorTypeUpdate {
	return stu.SetSettingsID(s.ID)
}

// Mutation returns the SensorTypeMutation object of the builder.
func (stu *SensorTypeUpdate) Mutation() *SensorTypeMutation {
	return stu.mutation
}

// ClearSensors clears all "sensors" edges to the Sensor entity.
func (stu *SensorTypeUpdate) ClearSensors() *SensorTypeUpdate {
	stu.mutation.ClearSensors()
	return stu
}

// RemoveSensorIDs removes the "sensors" edge to Sensor entities by IDs.
func (stu *SensorTypeUpdate) RemoveSensorIDs(ids ...int) *SensorTypeUpdate {
	stu.mutation.RemoveSensorIDs(ids...)
	return stu
}

// RemoveSensors removes "sensors" edges to Sensor entities.
func (stu *SensorTypeUpdate) RemoveSensors(s ...*Sensor) *SensorTypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return stu.RemoveSensorIDs(ids...)
}

// ClearSettings clears the "settings" edge to the SensorSettings entity.
func (stu *SensorTypeUpdate) ClearSettings() *SensorTypeUpdate {
	stu.mutation.ClearSettings()
	return stu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (stu *SensorTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, stu.sqlSave, stu.mutation, stu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (stu *SensorTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := stu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (stu *SensorTypeUpdate) Exec(ctx context.Context) error {
	_, err := stu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stu *SensorTypeUpdate) ExecX(ctx context.Context) {
	if err := stu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (stu *SensorTypeUpdate) check() error {
	if v, ok := stu.mutation.Name(); ok {
		if err := sensortype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SensorType.name": %w`, err)}
		}
	}
	if v, ok := stu.mutation.Model(); ok {
		if err := sensortype.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SensorType.model": %w`, err)}
		}
	}
	return nil
}

func (stu *SensorTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := stu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(sensortype.Table, sensortype.Columns, sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt))
	if ps := stu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := stu.mutation.Name(); ok {
		_spec.SetField(sensortype.FieldName, field.TypeString, value)
	}
	if value, ok := stu.mutation.Model(); ok {
		_spec.SetField(sensortype.FieldModel, field.TypeString, value)
	}
	if value, ok := stu.mutation.Manufacturer(); ok {
		_spec.SetField(sensortype.FieldManufacturer, field.TypeString, value)
	}
	if stu.mutation.ManufacturerCleared() {
		_spec.ClearField(sensortype.FieldManufacturer, field.TypeString)
	}
	if value, ok := stu.mutation.Description(); ok {
		_spec.SetField(sensortype.FieldDescription, field.TypeString, value)
	}
	if stu.mutation.DescriptionCleared() {
		_spec.ClearField(sensortype.FieldDescription, field.TypeString)
	}
	if stu.mutation.SensorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sensortype.SensorsTable,
			Columns: []string{sensortype.SensorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := stu.mutation.RemovedSensorsIDs(); len(nodes) > 0 && !stu.mutation.SensorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sensortype.SensorsTable,
			Columns: []string{sensortype.SensorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := stu.mutation.SensorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sensortype.SensorsTable,
			Columns: []string{sensortype.SensorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if stu.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sensortype.SettingsTable,
			Columns: []string{sensortype.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := stu.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sensortype.SettingsTable,
			Columns: []string{sensortype.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, stu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensortype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	stu.mutation.done = true
	return n, nil
}

// SensorTypeUpdateOne is the builder for updating a single SensorType entity.
type SensorTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SensorTypeMutation
}

// SetName sets the "name" field.
func (stuo *SensorTypeUpdateOne) SetName(s string) *SensorTypeUpdateOne {
	stuo.mutation.SetName(s)
	return stuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (stuo *SensorTypeUpdateOne) SetNillableName(s *string) *SensorTypeUpdateOne {
	if s != nil {
		stuo.SetName(*s)
	}
	return stuo
}

// SetModel sets the "model" field.
func (stuo *SensorTypeUpdateOne) SetModel(s string) *SensorTypeUpdateOne {
	stuo.mutation.SetModel(s)
	return stuo
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (stuo *SensorTypeUpdateOne) SetNillableModel(s *string) *SensorTypeUpdateOne {
	if s != nil {
		stuo.SetModel(*s)
	}
	return stuo
}

// SetManufacturer sets the "manufacturer" field.
func (stuo *SensorTypeUpdateOne) SetManufacturer(s string) *SensorTypeUpdateOne {
	stuo.mutation.SetManufacturer(s)
	return stuo
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (stuo *SensorTypeUpdateOne) SetNillableManufacturer(s *string) *SensorTypeUpdateOne {
	if s != nil {
		stuo.SetManufacturer(*s)
	}
	return stuo
}

// ClearManufacturer clears the value of the "manufacturer" field.
func (stuo *SensorTypeUpdateOne) ClearManufacturer() *SensorTypeUpdateOne {
	stuo.mutation.ClearManufacturer()
	return stuo
}

// SetDescription sets the "description" field.
func (stuo *SensorTypeUpdateOne) SetDescription(s string) *SensorTypeUpdateOne {
	stuo.mutation.SetDescription(s)
	return stuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (stuo *SensorTypeUpdateOne) SetNillableDescription(s *string) *SensorTypeUpdateOne {
	if s != nil {
		stuo.SetDescription(*s)
	}
	return stuo
}

// ClearDescription clears the value of the "description" field.
func (stuo *SensorTypeUpdateOne) ClearDescription() *SensorTypeUpdateOne {
	stuo.mutation.ClearDescription()
	return stuo
}

// AddSensorIDs adds the "sensors" edge to the Sensor entity by IDs.
func (stuo *SensorTypeUpdateOne) AddSensorIDs(ids ...int) *SensorTypeUpdateOne {
	stuo.mutation.AddSensorIDs(ids...)
	return stuo
}

// AddSensors adds the "sensors" edges to the Sensor entity.
func (stuo *SensorTypeUpdateOne) AddSensors(s ...*Sensor) *SensorTypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return stuo.AddSensorIDs(ids...)
}

// SetSettingsID sets the "settings" edge to the SensorSettings entity by ID.
func (stuo *SensorTypeUpdateOne) SetSettingsID(id int) *SensorTypeUpdateOne {
	stuo.mutation.SetSettingsID(id)
	return stuo
}

// SetNillableSettingsID sets the "settings" edge to the SensorSettings entity by ID if the given value is not nil.
func (stuo *SensorTypeUpdateOne) SetNillableSettingsID(id *int) *SensorTypeUpdateOne {
	if id != nil {
		stuo = stuo.SetSettingsID(*id)
	}
	return stuo
}

// SetSettings sets the "settings" edge to the SensorSettings entity.
func (stuo *SensorTypeUpdateOne) SetSettings(s *SensorSettings) *SensorTypeUpdateOne {
	return stuo.SetSettingsID(s.ID)
}

// Mutation returns the SensorTypeMutation object of the builder.
func (stuo *SensorTypeUpdateOne) Mutation() *SensorTypeMutation {
	return stuo.mutation
}

// ClearSensors clears all "sensors" edges to the Sensor entity.
func (stuo *SensorTypeUpdateOne) ClearSensors() *SensorTypeUpdateOne {
	stuo.mutation.ClearSensors()
	return stuo
}

// RemoveSensorIDs removes the "sensors" edge to Sensor entities by IDs.
func (stuo *SensorTypeUpdateOne) RemoveSensorIDs(ids ...int) *SensorTypeUpdateOne {
	stuo.mutation.RemoveSensorIDs(ids...)
	return stuo
}

// RemoveSensors removes "sensors" edges to Sensor entities.
func (stuo *SensorTypeUpdateOne) RemoveSensors(s ...*Sensor) *SensorTypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return stuo.RemoveSensorIDs(ids...)
}

// ClearSettings clears the "settings" edge to the SensorSettings entity.
func (stuo *SensorTypeUpdateOne) ClearSettings() *SensorTypeUpdateOne {
	stuo.mutation.ClearSettings()
	return stuo
}

// Where appends a list predicates to the SensorTypeUpdate builder.
func (stuo *SensorTypeUpdateOne) Where(ps ...predicate.SensorType) *SensorTypeUpdateOne {
	stuo.mutation.Where(ps...)
	return stuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (stuo *SensorTypeUpdateOne) Select(field string, fields ...string) *SensorTypeUpdateOne {
	stuo.fields = append([]string{field}, fields...)
	return stuo
}

// Save executes the query and returns the updated SensorType entity.
func (stuo *SensorTypeUpdateOne) Save(ctx context.Context) (*SensorType, error) {
	return withHooks(ctx, stuo.sqlSave, stuo.mutation, stuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (stuo *SensorTypeUpdateOne) SaveX(ctx context.Context) *SensorType {
	node, err := stuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (stuo *SensorTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := stuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stuo *SensorTypeUpdateOne) ExecX(ctx context.Context) {
	if err := stuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (stuo *SensorTypeUpdateOne) check() error {
	if v, ok := stuo.mutation.Name(); ok {
		if err := sensortype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SensorType.name": %w`, err)}
		}
	}
	if v, ok := stuo.mutation.Model(); ok {
		if err := sensortype.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SensorType.model": %w`, err)}
		}
	}
	return nil
}

func (stuo *SensorTypeUpdateOne) sqlSave(ctx context.Context) (_node *SensorType, err error) {
	if err := stuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sensortype.Table, sensortype.Columns, sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt))
	id, ok := stuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SensorType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := stuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sensortype.FieldID)
		for _, f := range fields {
			if !sensortype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sensortype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := stuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := stuo.mutation.Name(); ok {
		_spec.SetField(sensortype.FieldName, field.TypeString, value)
	}
	if value, ok := stuo.mutation.Model(); ok {
		_spec.SetField(sensortype.FieldModel, field.TypeString, value)
	}
	if value, ok := stuo.mutation.Manufacturer(); ok {
		_spec.SetField(sensortype.FieldManufacturer, field.TypeString, value)
	}
	if stuo.mutation.ManufacturerCleared() {
		_spec.ClearField(sensortype.FieldManufacturer, field.TypeString)
	}
	if value, ok := stuo.mutation.Description(); ok {
		_spec.SetField(sensortype.FieldDescription, field.TypeString, value)
	}
	if stuo.mutation.DescriptionCleared() {
		_spec.ClearField(sensortype.FieldDescription, field.TypeString)
	}
	if stuo.mutation.SensorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sensortype.SensorsTable,
			Columns: []string{sensortype.SensorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := stuo.mutation.RemovedSensorsIDs(); len(nodes) > 0 && !stuo.mutation.SensorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sensortype.SensorsTable,
			Columns: []string{sensortype.SensorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := stuo.mutation.SensorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sensortype.SensorsTable,
			Columns: []string{sensortype.SensorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensor.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if stuo.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sensortype.SettingsTable,
			Columns: []string{sensortype.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := stuo.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sensortype.SettingsTable,
			Columns: []string{sensortype.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SensorType{config: stuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, stuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensortype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	stuo.mutation.done = true
	return _node, nil
}
