// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/predicate"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensorsettings"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/sensortype"
)

// SensorSettingsUpdate is the builder for updating SensorSettings entities.
type SensorSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SensorSettingsMutation
}

// Where appends a list predicates to the SensorSettingsUpdate builder.
func (ssu *SensorSettingsUpdate) Where(ps ...predicate.SensorSettings) *SensorSettingsUpdate {
	ssu.mutation.Where(ps...)
	return ssu
}

// SetPollingIntervalSeconds sets the "polling_interval_seconds" field.
func (ssu *SensorSettingsUpdate) SetPollingIntervalSeconds(i int) *SensorSettingsUpdate {
	ssu.mutation.ResetPollingIntervalSeconds()
	ssu.mutation.SetPollingIntervalSeconds(i)
	return ssu
}

// SetNillablePollingIntervalSeconds sets the "polling_interval_seconds" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillablePollingIntervalSeconds(i *int) *SensorSettingsUpdate {
	if i != nil {
		ssu.SetPollingIntervalSeconds(*i)
	}
	return ssu
}

// AddPollingIntervalSeconds adds i to the "polling_interval_seconds" field.
func (ssu *SensorSettingsUpdate) AddPollingIntervalSeconds(i int) *SensorSettingsUpdate {
	ssu.mutation.AddPollingIntervalSeconds(i)
	return ssu
}

// SetMinValue sets the "min_value" field.
func (ssu *SensorSettingsUpdate) SetMinValue(f float64) *SensorSettingsUpdate {
	ssu.mutation.ResetMinValue()
	ssu.mutation.SetMinValue(f)
	return ssu
}

// SetNillableMinValue sets the "min_value" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableMinValue(f *float64) *SensorSettingsUpdate {
	if f != nil {
		ssu.SetMinValue(*f)
	}
	return ssu
}

// AddMinValue adds f to the "min_value" field.
func (ssu *SensorSettingsUpdate) AddMinValue(f float64) *SensorSettingsUpdate {
	ssu.mutation.AddMinValue(f)
	return ssu
}

// ClearMinValue clears the value of the "min_value" field.
func (ssu *SensorSettingsUpdate) ClearMinValue() *SensorSettingsUpdate {
	ssu.mutation.ClearMinValue()
	return ssu
}

// SetMaxValue sets the "max_value" field.
func (ssu *SensorSettingsUpdate) SetMaxValue(f float64) *SensorSettingsUpdate {
	ssu.mutation.ResetMaxValue()
	ssu.mutation.SetMaxValue(f)
	return ssu
}

// SetNillableMaxValue sets the "max_value" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableMaxValue(f *float64) *SensorSettingsUpdate {
	if f != nil {
		ssu.SetMaxValue(*f)
	}
	return ssu
}

// AddMaxValue adds f to the "max_value" field.
func (ssu *SensorSettingsUpdate) AddMaxValue(f float64) *SensorSettingsUpdate {
	ssu.mutation.AddMaxValue(f)
	return ssu
}

// ClearMaxValue clears the value of the "max_value" field.
func (ssu *SensorSettingsUpdate) ClearMaxValue() *SensorSettingsUpdate {
	ssu.mutation.ClearMaxValue()
	return ssu
}

// SetMeanValue sets the "mean_value" field.
func (ssu *SensorSettingsUpdate) SetMeanValue(f float64) *SensorSettingsUpdate {
	ssu.mutation.ResetMeanValue()
	ssu.mutation.SetMeanValue(f)
	return ssu
}

// SetNillableMeanValue sets the "mean_value" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableMeanValue(f *float64) *SensorSettingsUpdate {
	if f != nil {
		ssu.SetMeanValue(*f)
	}
	return ssu
}

// AddMeanValue adds f to the "mean_value" field.
func (ssu *SensorSettingsUpdate) AddMeanValue(f float64) *SensorSettingsUpdate {
	ssu.mutation.AddMeanValue(f)
	return ssu
}

// ClearMeanValue clears the value of the "mean_value" field.
func (ssu *SensorSettingsUpdate) ClearMeanValue() *SensorSettingsUpdate {
	ssu.mutation.ClearMeanValue()
	return ssu
}

// SetStdDeviation sets the "std_deviation" field.
func (ssu *SensorSettingsUpdate) SetStdDeviation(f float64) *SensorSettingsUpdate {
	ssu.mutation.ResetStdDeviation()
	ssu.mutation.SetStdDeviation(f)
	return ssu
}

// SetNillableStdDeviation sets the "std_deviation" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableStdDeviation(f *float64) *SensorSettingsUpdate {
	if f != nil {
		ssu.SetStdDeviation(*f)
	}
	return ssu
}

// AddStdDeviation adds f to the "std_deviation" field.
func (ssu *SensorSettingsUpdate) AddStdDeviation(f float64) *SensorSettingsUpdate {
	ssu.mutation.AddStdDeviation(f)
	return ssu
}

// ClearStdDeviation clears the value of the "std_deviation" field.
func (ssu *SensorSettingsUpdate) ClearStdDeviation() *SensorSettingsUpdate {
	ssu.mutation.ClearStdDeviation()
	return ssu
}

// SetDriftFactor sets the "drift_factor" field.
func (ssu *SensorSettingsUpdate) SetDriftFactor(f float64) *SensorSettingsUpdate {
	ssu.mutation.ResetDriftFactor()
	ssu.mutation.SetDriftFactor(f)
	return ssu
}

// SetNillableDriftFactor sets the "drift_factor" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableDriftFactor(f *float64) *SensorSettingsUpdate {
	if f != nil {
		ssu.SetDriftFactor(*f)
	}
	return ssu
}

// AddDriftFactor adds f to the "drift_factor" field.
func (ssu *SensorSettingsUpdate) AddDriftFactor(f float64) *SensorSettingsUpdate {
	ssu.mutation.AddDriftFactor(f)
	return ssu
}

// SetSeasonalVariation sets the "seasonal_variation" field.
func (ssu *SensorSettingsUpdate) SetSeasonalVariation(b bool) *SensorSettingsUpdate {
	ssu.mutation.SetSeasonalVariation(b)
	return ssu
}

// SetNillableSeasonalVariation sets the "seasonal_variation" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableSeasonalVariation(b *bool) *SensorSettingsUpdate {
	if b != nil {
		ssu.SetSeasonalVariation(*b)
	}
	return ssu
}

// SetCyclePeriodSeconds sets the "cycle_period_seconds" field.
func (ssu *SensorSettingsUpdate) SetCyclePeriodSeconds(i int) *SensorSettingsUpdate {
	ssu.mutation.ResetCyclePeriodSeconds()
	ssu.mutation.SetCyclePeriodSeconds(i)
	return ssu
}

// SetNillableCyclePeriodSeconds sets the "cycle_period_seconds" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableCyclePeriodSeconds(i *int) *SensorSettingsUpdate {
	if i != nil {
		ssu.SetCyclePeriodSeconds(*i)
	}
	return ssu
}

// AddCyclePeriodSeconds adds i to the "cycle_period_seconds" field.
func (ssu *SensorSettingsUpdate) AddCyclePeriodSeconds(i int) *SensorSettingsUpdate {
	ssu.mutation.AddCyclePeriodSeconds(i)
	return ssu
}

// ClearCyclePeriodSeconds clears the value of the "cycle_period_seconds" field.
func (ssu *SensorSettingsUpdate) ClearCyclePeriodSeconds() *SensorSettingsUpdate {
	ssu.mutation.ClearCyclePeriodSeconds()
	return ssu
}

// SetNoiseFactor sets the "noise_factor" field.
func (ssu *SensorSettingsUpdate) SetNoiseFactor(f float64) *SensorSettingsUpdate {
	ssu.mutation.ResetNoiseFactor()
	ssu.mutation.SetNoiseFactor(f)
	return ssu
}

// SetNillableNoiseFactor sets the "noise_factor" field if the given value is not nil.
func (ssu *SensorSettingsUpdate) SetNillableNoiseFactor(f *float64) *SensorSettingsUpdate {
	if f != nil {
		ssu.SetNoiseFactor(*f)
	}
	return ssu
}

// AddNoiseFactor adds f to the "noise_factor" field.
func (ssu *SensorSettingsUpdate) AddNoiseFactor(f float64) *SensorSettingsUpdate {
	ssu.mutation.AddNoiseFactor(f)
	return ssu
}

// SetPossibleValues sets the "possible_values" field.
func (ssu *SensorSettingsUpdate) SetPossibleValues(s []string) *SensorSettingsUpdate {
	ssu.mutation.SetPossibleValues(s)
	return ssu
}

// AppendPossibleValues appends s to the "possible_values" field.
func (ssu *SensorSettingsUpdate) AppendPossibleValues(s []string) *SensorSettingsUpdate {
	ssu.mutation.AppendPossibleValues(s)
	return ssu
}

// ClearPossibleValues clears the value of the "possible_values" field.
func (ssu *SensorSettingsUpdate) ClearPossibleValues() *SensorSettingsUpdate {
	ssu.mutation.ClearPossibleValues()
	return ssu
}

// SetAnomalyConfig sets the "anomaly_config" field.
func (ssu *SensorSettingsUpdate) SetAnomalyConfig(m map[string]interface{}) *SensorSettingsUpdate {
	ssu.mutation.SetAnomalyConfig(m)
	return ssu
}

// ClearAnomalyConfig clears the value of the "anomaly_config" field.
func (ssu *SensorSettingsUpdate) ClearAnomalyConfig() *SensorSettingsUpdate {
	ssu.mutation.ClearAnomalyConfig()
	return ssu
}

// SetSensorTypeID sets the "sensor_type" edge to the SensorType entity by ID.
func (ssu *SensorSettingsUpdate) SetSensorTypeID(id int) *SensorSettingsUpdate {
	ssu.mutation.SetSensorTypeID(id)
	return ssu
}

// SetSensorType sets the "sensor_type" edge to the SensorType entity.
func (ssu *SensorSettingsUpdate) SetSensorType(s *SensorType) *SensorSettingsUpdate {
	return ssu.SetSensorTypeID(s.ID)
}

// Mutation returns the SensorSettingsMutation object of the builder.
func (ssu *SensorSettingsUpdate) Mutation() *SensorSettingsMutation {
	return ssu.mutation
}

// ClearSensorType clears the "sensor_type" edge to the SensorType entity.
func (ssu *SensorSettingsUpdate) ClearSensorType() *SensorSettingsUpdate {
	ssu.mutation.ClearSensorType()
	return ssu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ssu *SensorSettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ssu.sqlSave, ssu.mutation, ssu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssu *SensorSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := ssu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ssu *SensorSettingsUpdate) Exec(ctx context.Context) error {
	_, err := ssu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssu *SensorSettingsUpdate) ExecX(ctx context.Context) {
	if err := ssu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssu *SensorSettingsUpdate) check() error {
	if v, ok := ssu.mutation.PollingIntervalSeconds(); ok {
		if err := sensorsettings.PollingIntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "polling_interval_seconds", err: fmt.Errorf(`ent: validator failed for field "SensorSettings.polling_interval_seconds": %w`, err)}
		}
	}
	if ssu.mutation.SensorTypeCleared() && len(ssu.mutation.SensorTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SensorSettings.sensor_type"`)
	}
	return nil
}

func (ssu *SensorSettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ssu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(sensorsettings.Table, sensorsettings.Columns, sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt))
	if ps := ssu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssu.mutation.PollingIntervalSeconds(); ok {
		_spec.SetField(sensorsettings.FieldPollingIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := ssu.mutation.AddedPollingIntervalSeconds(); ok {
		_spec.AddField(sensorsettings.FieldPollingIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := ssu.mutation.MinValue(); ok {
		_spec.SetField(sensorsettings.FieldMinValue, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.AddedMinValue(); ok {
		_spec.AddField(sensorsettings.FieldMinValue, field.TypeFloat64, value)
	}
	if ssu.mutation.MinValueCleared() {
		_spec.ClearField(sensorsettings.FieldMinValue, field.TypeFloat64)
	}
	if value, ok := ssu.mutation.MaxValue(); ok {
		_spec.SetField(sensorsettings.FieldMaxValue, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.AddedMaxValue(); ok {
		_spec.AddField(sensorsettings.FieldMaxValue, field.TypeFloat64, value)
	}
	if ssu.mutation.MaxValueCleared() {
		_spec.ClearField(sensorsettings.FieldMaxValue, field.TypeFloat64)
	}
	if value, ok := ssu.mutation.MeanValue(); ok {
		_spec.SetField(sensorsettings.FieldMeanValue, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.AddedMeanValue(); ok {
		_spec.AddField(sensorsettings.FieldMeanValue, field.TypeFloat64, value)
	}
	if ssu.mutation.MeanValueCleared() {
		_spec.ClearField(sensorsettings.FieldMeanValue, field.TypeFloat64)
	}
	if value, ok := ssu.mutation.StdDeviation(); ok {
		_spec.SetField(sensorsettings.FieldStdDeviation, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.AddedStdDeviation(); ok {
		_spec.AddField(sensorsettings.FieldStdDeviation, field.TypeFloat64, value)
	}
	if ssu.mutation.StdDeviationCleared() {
		_spec.ClearField(sensorsettings.FieldStdDeviation, field.TypeFloat64)
	}
	if value, ok := ssu.mutation.DriftFactor(); ok {
		_spec.SetField(sensorsettings.FieldDriftFactor, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.AddedDriftFactor(); ok {
		_spec.AddField(sensorsettings.FieldDriftFactor, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.SeasonalVariation(); ok {
		_spec.SetField(sensorsettings.FieldSeasonalVariation, field.TypeBool, value)
	}
	if value, ok := ssu.mutation.CyclePeriodSeconds(); ok {
		_spec.SetField(sensorsettings.FieldCyclePeriodSeconds, field.TypeInt, value)
	}
	if value, ok := ssu.mutation.AddedCyclePeriodSeconds(); ok {
		_spec.AddField(sensorsettings.FieldCyclePeriodSeconds, field.TypeInt, value)
	}
	if ssu.mutation.CyclePeriodSecondsCleared() {
		_spec.ClearField(sensorsettings.FieldCyclePeriodSeconds, field.TypeInt)
	}
	if value, ok := ssu.mutation.NoiseFactor(); ok {
		_spec.SetField(sensorsettings.FieldNoiseFactor, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.AddedNoiseFactor(); ok {
		_spec.AddField(sensorsettings.FieldNoiseFactor, field.TypeFloat64, value)
	}
	if value, ok := ssu.mutation.PossibleValues(); ok {
		_spec.SetField(sensorsettings.FieldPossibleValues, field.TypeJSON, value)
	}
	if value, ok := ssu.mutation.AppendedPossibleValues(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sensorsettings.FieldPossibleValues, value)
		})
	}
	if ssu.mutation.PossibleValuesCleared() {
		_spec.ClearField(sensorsettings.FieldPossibleValues, field.TypeJSON)
	}
	if value, ok := ssu.mutation.AnomalyConfig(); ok {
		_spec.SetField(sensorsettings.FieldAnomalyConfig, field.TypeJSON, value)
	}
	if ssu.mutation.AnomalyConfigCleared() {
		_spec.ClearField(sensorsettings.FieldAnomalyConfig, field.TypeJSON)
	}
	if ssu.mutation.SensorTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sensorsettings.SensorTypeTable,
			Columns: []string{sensorsettings.SensorTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssu.mutation.SensorTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sensorsettings.SensorTypeTable,
			Columns: []string{sensorsettings.SensorTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ssu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensorsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ssu.mutation.done = true
	return n, nil
}

// SensorSettingsUpdateOne is the builder for updating a single SensorSettings entity.
type SensorSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SensorSettingsMutation
}

// SetPollingIntervalSeconds sets the "polling_interval_seconds" field.
func (ssuo *SensorSettingsUpdateOne) SetPollingIntervalSeconds(i int) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetPollingIntervalSeconds()
	ssuo.mutation.SetPollingIntervalSeconds(i)
	return ssuo
}

// SetNillablePollingIntervalSeconds sets the "polling_interval_seconds" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillablePollingIntervalSeconds(i *int) *SensorSettingsUpdateOne {
	if i != nil {
		ssuo.SetPollingIntervalSeconds(*i)
	}
	return ssuo
}

// AddPollingIntervalSeconds adds i to the "polling_interval_seconds" field.
func (ssuo *SensorSettingsUpdateOne) AddPollingIntervalSeconds(i int) *SensorSettingsUpdateOne {
	ssuo.mutation.AddPollingIntervalSeconds(i)
	return ssuo
}

// SetMinValue sets the "min_value" field.
func (ssuo *SensorSettingsUpdateOne) SetMinValue(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetMinValue()
	ssuo.mutation.SetMinValue(f)
	return ssuo
}

// SetNillableMinValue sets the "min_value" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableMinValue(f *float64) *SensorSettingsUpdateOne {
	if f != nil {
		ssuo.SetMinValue(*f)
	}
	return ssuo
}

// AddMinValue adds f to the "min_value" field.
func (ssuo *SensorSettingsUpdateOne) AddMinValue(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.AddMinValue(f)
	return ssuo
}

// ClearMinValue clears the value of the "min_value" field.
func (ssuo *SensorSettingsUpdateOne) ClearMinValue() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearMinValue()
	return ssuo
}

// SetMaxValue sets the "max_value" field.
func (ssuo *SensorSettingsUpdateOne) SetMaxValue(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetMaxValue()
	ssuo.mutation.SetMaxValue(f)
	return ssuo
}

// SetNillableMaxValue sets the "max_value" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableMaxValue(f *float64) *SensorSettingsUpdateOne {
	if f != nil {
		ssuo.SetMaxValue(*f)
	}
	return ssuo
}

// AddMaxValue adds f to the "max_value" field.
func (ssuo *SensorSettingsUpdateOne) AddMaxValue(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.AddMaxValue(f)
	return ssuo
}

// ClearMaxValue clears the value of the "max_value" field.
func (ssuo *SensorSettingsUpdateOne) ClearMaxValue() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearMaxValue()
	return ssuo
}

// SetMeanValue sets the "mean_value" field.
func (ssuo *SensorSettingsUpdateOne) SetMeanValue(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetMeanValue()
	ssuo.mutation.SetMeanValue(f)
	return ssuo
}

// SetNillableMeanValue sets the "mean_value" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableMeanValue(f *float64) *SensorSettingsUpdateOne {
	if f != nil {
		ssuo.SetMeanValue(*f)
	}
	return ssuo
}

// AddMeanValue adds f to the "mean_value" field.
func (ssuo *SensorSettingsUpdateOne) AddMeanValue(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.AddMeanValue(f)
	return ssuo
}

// ClearMeanValue clears the value of the "mean_value" field.
func (ssuo *SensorSettingsUpdateOne) ClearMeanValue() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearMeanValue()
	return ssuo
}

// SetStdDeviation sets the "std_deviation" field.
func (ssuo *SensorSettingsUpdateOne) SetStdDeviation(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetStdDeviation()
	ssuo.mutation.SetStdDeviation(f)
	return ssuo
}

// SetNillableStdDeviation sets the "std_deviation" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableStdDeviation(f *float64) *SensorSettingsUpdateOne {
	if f != nil {
		ssuo.SetStdDeviation(*f)
	}
	return ssuo
}

// AddStdDeviation adds f to the "std_deviation" field.
func (ssuo *SensorSettingsUpdateOne) AddStdDeviation(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.AddStdDeviation(f)
	return ssuo
}

// ClearStdDeviation clears the value of the "std_deviation" field.
func (ssuo *SensorSettingsUpdateOne) ClearStdDeviation() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearStdDeviation()
	return ssuo
}

// SetDriftFactor sets the "drift_factor" field.
func (ssuo *SensorSettingsUpdateOne) SetDriftFactor(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetDriftFactor()
	ssuo.mutation.SetDriftFactor(f)
	return ssuo
}

// SetNillableDriftFactor sets the "drift_factor" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableDriftFactor(f *float64) *SensorSettingsUpdateOne {
	if f != nil {
		ssuo.SetDriftFactor(*f)
	}
	return ssuo
}

// AddDriftFactor adds f to the "drift_factor" field.
func (ssuo *SensorSettingsUpdateOne) AddDriftFactor(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.AddDriftFactor(f)
	return ssuo
}

// SetSeasonalVariation sets the "seasonal_variation" field.
func (ssuo *SensorSettingsUpdateOne) SetSeasonalVariation(b bool) *SensorSettingsUpdateOne {
	ssuo.mutation.SetSeasonalVariation(b)
	return ssuo
}

// SetNillableSeasonalVariation sets the "seasonal_variation" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableSeasonalVariation(b *bool) *SensorSettingsUpdateOne {
	if b != nil {
		ssuo.SetSeasonalVariation(*b)
	}
	return ssuo
}

// SetCyclePeriodSeconds sets the "cycle_period_seconds" field.
func (ssuo *SensorSettingsUpdateOne) SetCyclePeriodSeconds(i int) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetCyclePeriodSeconds()
	ssuo.mutation.SetCyclePeriodSeconds(i)
	return ssuo
}

// SetNillableCyclePeriodSeconds sets the "cycle_period_seconds" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableCyclePeriodSeconds(i *int) *SensorSettingsUpdateOne {
	if i != nil {
		ssuo.SetCyclePeriodSeconds(*i)
	}
	return ssuo
}

// AddCyclePeriodSeconds adds i to the "cycle_period_seconds" field.
func (ssuo *SensorSettingsUpdateOne) AddCyclePeriodSeconds(i int) *SensorSettingsUpdateOne {
	ssuo.mutation.AddCyclePeriodSeconds(i)
	return ssuo
}

// ClearCyclePeriodSeconds clears the value of the "cycle_period_seconds" field.
func (ssuo *SensorSettingsUpdateOne) ClearCyclePeriodSeconds() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearCyclePeriodSeconds()
	return ssuo
}

// SetNoiseFactor sets the "noise_factor" field.
func (ssuo *SensorSettingsUpdateOne) SetNoiseFactor(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.ResetNoiseFactor()
	ssuo.mutation.SetNoiseFactor(f)
	return ssuo
}

// SetNillableNoiseFactor sets the "noise_factor" field if the given value is not nil.
func (ssuo *SensorSettingsUpdateOne) SetNillableNoiseFactor(f *float64) *SensorSettingsUpdateOne {
	if f != nil {
		ssuo.SetNoiseFactor(*f)
	}
	return ssuo
}

// AddNoiseFactor adds f to the "noise_factor" field.
func (ssuo *SensorSettingsUpdateOne) AddNoiseFactor(f float64) *SensorSettingsUpdateOne {
	ssuo.mutation.AddNoiseFactor(f)
	return ssuo
}

// SetPossibleValues sets the "possible_values" field.
func (ssuo *SensorSettingsUpdateOne) SetPossibleValues(s []string) *SensorSettingsUpdateOne {
	ssuo.mutation.SetPossibleValues(s)
	return ssuo
}

// AppendPossibleValues appends s to the "possible_values" field.
func (ssuo *SensorSettingsUpdateOne) AppendPossibleValues(s []string) *SensorSettingsUpdateOne {
	ssuo.mutation.AppendPossibleValues(s)
	return ssuo
}

// ClearPossibleValues clears the value of the "possible_values" field.
func (ssuo *SensorSettingsUpdateOne) ClearPossibleValues() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearPossibleValues()
	return ssuo
}

// SetAnomalyConfig sets the "anomaly_config" field.
func (ssuo *SensorSettingsUpdateOne) SetAnomalyConfig(m map[string]interface{}) *SensorSettingsUpdateOne {
	ssuo.mutation.SetAnomalyConfig(m)
	return ssuo
}

// ClearAnomalyConfig clears the value of the "anomaly_config" field.
func (ssuo *SensorSettingsUpdateOne) ClearAnomalyConfig() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearAnomalyConfig()
	return ssuo
}

// SetSensorTypeID sets the "sensor_type" edge to the SensorType entity by ID.
func (ssuo *SensorSettingsUpdateOne) SetSensorTypeID(id int) *SensorSettingsUpdateOne {
	ssuo.mutation.SetSensorTypeID(id)
	return ssuo
}

// SetSensorType sets the "sensor_type" edge to the SensorType entity.
func (ssuo *SensorSettingsUpdateOne) SetSensorType(s *SensorType) *SensorSettingsUpdateOne {
	return ssuo.SetSensorTypeID(s.ID)
}

// Mutation returns the SensorSettingsMutation object of the builder.
func (ssuo *SensorSettingsUpdateOne) Mutation() *SensorSettingsMutation {
	return ssuo.mutation
}

// ClearSensorType clears the "sensor_type" edge to the SensorType entity.
func (ssuo *SensorSettingsUpdateOne) ClearSensorType() *SensorSettingsUpdateOne {
	ssuo.mutation.ClearSensorType()
	return ssuo
}

// Where appends a list predicates to the SensorSettingsUpdate builder.
func (ssuo *SensorSettingsUpdateOne) Where(ps ...predicate.SensorSettings) *SensorSettingsUpdateOne {
	ssuo.mutation.Where(ps...)
	return ssuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ssuo *SensorSettingsUpdateOne) Select(field string, fields ...string) *SensorSettingsUpdateOne {
	ssuo.fields = append([]string{field}, fields...)
	return ssuo
}

// Save executes the query and returns the updated SensorSettings entity.
func (ssuo *SensorSettingsUpdateOne) Save(ctx context.Context) (*SensorSettings, error) {
	return withHooks(ctx, ssuo.sqlSave, ssuo.mutation, ssuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssuo *SensorSettingsUpdateOne) SaveX(ctx context.Context) *SensorSettings {
	node, err := ssuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ssuo *SensorSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := ssuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssuo *SensorSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := ssuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssuo *SensorSettingsUpdateOne) check() error {
	if v, ok := ssuo.mutation.PollingIntervalSeconds(); ok {
		if err := sensorsettings.PollingIntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "polling_interval_seconds", err: fmt.Errorf(`ent: validator failed for field "SensorSettings.polling_interval_seconds": %w`, err)}
		}
	}
	if ssuo.mutation.SensorTypeCleared() && len(ssuo.mutation.SensorTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SensorSettings.sensor_type"`)
	}
	return nil
}

func (ssuo *SensorSettingsUpdateOne) sqlSave(ctx context.Context) (_node *SensorSettings, err error) {
	if err := ssuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sensorsettings.Table, sensorsettings.Columns, sqlgraph.NewFieldSpec(sensorsettings.FieldID, field.TypeInt))
	id, ok := ssuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SensorSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ssuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sensorsettings.FieldID)
		for _, f := range fields {
			if !sensorsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sensorsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ssuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssuo.mutation.PollingIntervalSeconds(); ok {
		_spec.SetField(sensorsettings.FieldPollingIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := ssuo.mutation.AddedPollingIntervalSeconds(); ok {
		_spec.AddField(sensorsettings.FieldPollingIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := ssuo.mutation.MinValue(); ok {
		_spec.SetField(sensorsettings.FieldMinValue, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.AddedMinValue(); ok {
		_spec.AddField(sensorsettings.FieldMinValue, field.TypeFloat64, value)
	}
	if ssuo.mutation.MinValueCleared() {
		_spec.ClearField(sensorsettings.FieldMinValue, field.TypeFloat64)
	}
	if value, ok := ssuo.mutation.MaxValue(); ok {
		_spec.SetField(sensorsettings.FieldMaxValue, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.AddedMaxValue(); ok {
		_spec.AddField(sensorsettings.FieldMaxValue, field.TypeFloat64, value)
	}
	if ssuo.mutation.MaxValueCleared() {
		_spec.ClearField(sensorsettings.FieldMaxValue, field.TypeFloat64)
	}
	if value, ok := ssuo.mutation.MeanValue(); ok {
		_spec.SetField(sensorsettings.FieldMeanValue, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.AddedMeanValue(); ok {
		_spec.AddField(sensorsettings.FieldMeanValue, field.TypeFloat64, value)
	}
	if ssuo.mutation.MeanValueCleared() {
		_spec.ClearField(sensorsettings.FieldMeanValue, field.TypeFloat64)
	}
	if value, ok := ssuo.mutation.StdDeviation(); ok {
		_spec.SetField(sensorsettings.FieldStdDeviation, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.AddedStdDeviation(); ok {
		_spec.AddField(sensorsettings.FieldStdDeviation, field.TypeFloat64, value)
	}
	if ssuo.mutation.StdDeviationCleared() {
		_spec.ClearField(sensorsettings.FieldStdDeviation, field.TypeFloat64)
	}
	if value, ok := ssuo.mutation.DriftFactor(); ok {
		_spec.SetField(sensorsettings.FieldDriftFactor, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.AddedDriftFactor(); ok {
		_spec.AddField(sensorsettings.FieldDriftFactor, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.SeasonalVariation(); ok {
		_spec.SetField(sensorsettings.FieldSeasonalVariation, field.TypeBool, value)
	}
	if value, ok := ssuo.mutation.CyclePeriodSeconds(); ok {
		_spec.SetField(sensorsettings.FieldCyclePeriodSeconds, field.TypeInt, value)
	}
	if value, ok := ssuo.mutation.AddedCyclePeriodSeconds(); ok {
		_spec.AddField(sensorsettings.FieldCyclePeriodSeconds, field.TypeInt, value)
	}
	if ssuo.mutation.CyclePeriodSecondsCleared() {
		_spec.ClearField(sensorsettings.FieldCyclePeriodSeconds, field.TypeInt)
	}
	if value, ok := ssuo.mutation.NoiseFactor(); ok {
		_spec.SetField(sensorsettings.FieldNoiseFactor, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.AddedNoiseFactor(); ok {
		_spec.AddField(sensorsettings.FieldNoiseFactor, field.TypeFloat64, value)
	}
	if value, ok := ssuo.mutation.PossibleValues(); ok {
		_spec.SetField(sensorsettings.FieldPossibleValues, field.TypeJSON, value)
	}
	if value, ok := ssuo.mutation.AppendedPossibleValues(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sensorsettings.FieldPossibleValues, value)
		})
	}
	if ssuo.mutation.PossibleValuesCleared() {
		_spec.ClearField(sensorsettings.FieldPossibleValues, field.TypeJSON)
	}
	if value, ok := ssuo.mutation.AnomalyConfig(); ok {
		_spec.SetField(sensorsettings.FieldAnomalyConfig, field.TypeJSON, value)
	}
	if ssuo.mutation.AnomalyConfigCleared() {
		_spec.ClearField(sensorsettings.FieldAnomalyConfig, field.TypeJSON)
	}
	if ssuo.mutation.SensorTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sensorsettings.SensorTypeTable,
			Columns: []string{sensorsettings.SensorTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ssuo.mutation.SensorTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sensorsettings.SensorTypeTable,
			Columns: []string{sensorsettings.SensorTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sensortype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SensorSettings{config: ssuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ssuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sensorsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ssuo.mutation.done = true
	return _node, nil
}
