// Code generated by ent, DO NOT EDIT.

package sensorsettings

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sensorsettings type in the database.
	Label = "sensor_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPollingIntervalSeconds holds the string denoting the polling_interval_seconds field in the database.
	FieldPollingIntervalSeconds = "polling_interval_seconds"
	// FieldMinValue holds the string denoting the min_value field in the database.
	FieldMinValue = "min_value"
	// FieldMaxValue holds the string denoting the max_value field in the database.
	FieldMaxValue = "max_value"
	// FieldMeanValue holds the string denoting the mean_value field in the database.
	FieldMeanValue = "mean_value"
	// FieldStdDeviation holds the string denoting the std_deviation field in the database.
	FieldStdDeviation = "std_deviation"
	// FieldDriftFactor holds the string denoting the drift_factor field in the database.
	FieldDriftFactor = "drift_factor"
	// FieldSeasonalVariation holds the string denoting the seasonal_variation field in the database.
	FieldSeasonalVariation = "seasonal_variation"
	// FieldCyclePeriodSeconds holds the string denoting the cycle_period_seconds field in the database.
	FieldCyclePeriodSeconds = "cycle_period_seconds"
	// FieldNoiseFactor holds the string denoting the noise_factor field in the database.
	FieldNoiseFactor = "noise_factor"
	// FieldPossibleValues holds the string denoting the possible_values field in the database.
	FieldPossibleValues = "possible_values"
	// FieldAnomalyConfig holds the string denoting the anomaly_config field in the database.
	FieldAnomalyConfig = "anomaly_config"
	// EdgeSensorType holds the string denoting the sensor_type edge name in mutations.
	EdgeSensorType = "sensor_type"
	// Table holds the table name of the sensorsettings in the database.
	Table = "sensor_settings"
	// SensorTypeTable is the table that holds the sensor_type relation/edge.
	SensorTypeTable = "sensor_settings"
	// SensorTypeInverseTable is the table name for the SensorType entity.
	// It exists in this package in order to avoid circular dependency with the "sensortype" package.
	SensorTypeInverseTable = "sensor_types"
	// SensorTypeColumn is the table column denoting the sensor_type relation/edge.
	SensorTypeColumn = "sensor_type_settings"
)

// Columns holds all SQL columns for sensorsettings fields.
var Columns = []string{
	FieldID,
	FieldPollingIntervalSeconds,
	FieldMinValue,
	FieldMaxValue,
	FieldMeanValue,
	FieldStdDeviation,
	FieldDriftFactor,
	FieldSeasonalVariation,
	FieldCyclePeriodSeconds,
	FieldNoiseFactor,
	FieldPossibleValues,
	FieldAnomalyConfig,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "sensor_settings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"sensor_type_settings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPollingIntervalSeconds holds the default value on creation for the "polling_interval_seconds" field.
	DefaultPollingIntervalSeconds int
	// PollingIntervalSecondsValidator is a validator for the "polling_interval_seconds" field. It is called by the builders before save.
	PollingIntervalSecondsValidator func(int) error
	// DefaultDriftFactor holds the default value on creation for the "drift_factor" field.
	DefaultDriftFactor float64
	// DefaultSeasonalVariation holds the default value on creation for the "seasonal_variation" field.
	DefaultSeasonalVariation bool
	// DefaultNoiseFactor holds the default value on creation for the "noise_factor" field.
	DefaultNoiseFactor float64
)

// OrderOption defines the ordering options for the SensorSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPollingIntervalSeconds orders the results by the polling_interval_seconds field.
func ByPollingIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPollingIntervalSeconds, opts...).ToFunc()
}

// ByMinValue orders the results by the min_value field.
func ByMinValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinValue, opts...).ToFunc()
}

// ByMaxValue orders the results by the max_value field.
func ByMaxValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxValue, opts...).ToFunc()
}

// ByMeanValue orders the results by the mean_value field.
func ByMeanValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeanValue, opts...).ToFunc()
}

// ByStdDeviation orders the results by the std_deviation field.
func ByStdDeviation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStdDeviation, opts...).ToFunc()
}

// ByDriftFactor orders the results by the drift_factor field.
func ByDriftFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriftFactor, opts...).ToFunc()
}

// BySeasonalVariation orders the results by the seasonal_variation field.
func BySeasonalVariation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeasonalVariation, opts...).ToFunc()
}

// ByCyclePeriodSeconds orders the results by the cycle_period_seconds field.
func ByCyclePeriodSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCyclePeriodSeconds, opts...).ToFunc()
}

// ByNoiseFactor orders the results by the noise_factor field.
func ByNoiseFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoiseFactor, opts...).ToFunc()
}

// BySensorTypeField orders the results by sensor_type field.
func BySensorTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSensorTypeStep(), sql.OrderByField(field, opts...))
	}
}
func newSensorTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SensorTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, SensorTypeTable, SensorTypeColumn),
	)
}
