// Code generated by ent, DO NOT EDIT.

package sensorsettings

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/skni-kod/iot-monitor-backend/pkg/sensor-simulator/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldID, id))
}

// PollingIntervalSeconds applies equality check predicate on the "polling_interval_seconds" field. It's identical to PollingIntervalSecondsEQ.
func PollingIntervalSeconds(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldPollingIntervalSeconds, v))
}

// MinValue applies equality check predicate on the "min_value" field. It's identical to MinValueEQ.
func MinValue(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldMinValue, v))
}

// MaxValue applies equality check predicate on the "max_value" field. It's identical to MaxValueEQ.
func MaxValue(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldMaxValue, v))
}

// MeanValue applies equality check predicate on the "mean_value" field. It's identical to MeanValueEQ.
func MeanValue(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldMeanValue, v))
}

// StdDeviation applies equality check predicate on the "std_deviation" field. It's identical to StdDeviationEQ.
func StdDeviation(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldStdDeviation, v))
}

// DriftFactor applies equality check predicate on the "drift_factor" field. It's identical to DriftFactorEQ.
func DriftFactor(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldDriftFactor, v))
}

// SeasonalVariation applies equality check predicate on the "seasonal_variation" field. It's identical to SeasonalVariationEQ.
func SeasonalVariation(v bool) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldSeasonalVariation, v))
}

// CyclePeriodSeconds applies equality check predicate on the "cycle_period_seconds" field. It's identical to CyclePeriodSecondsEQ.
func CyclePeriodSeconds(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldCyclePeriodSeconds, v))
}

// NoiseFactor applies equality check predicate on the "noise_factor" field. It's identical to NoiseFactorEQ.
func NoiseFactor(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldNoiseFactor, v))
}

// PollingIntervalSecondsEQ applies the EQ predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsEQ(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldPollingIntervalSeconds, v))
}

// PollingIntervalSecondsNEQ applies the NEQ predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsNEQ(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldPollingIntervalSeconds, v))
}

// PollingIntervalSecondsIn applies the In predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsIn(vs ...int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldPollingIntervalSeconds, vs...))
}

// PollingIntervalSecondsNotIn applies the NotIn predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsNotIn(vs ...int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldPollingIntervalSeconds, vs...))
}

// PollingIntervalSecondsGT applies the GT predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsGT(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldPollingIntervalSeconds, v))
}

// PollingIntervalSecondsGTE applies the GTE predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsGTE(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldPollingIntervalSeconds, v))
}

// PollingIntervalSecondsLT applies the LT predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsLT(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldPollingIntervalSeconds, v))
}

// PollingIntervalSecondsLTE applies the LTE predicate on the "polling_interval_seconds" field.
func PollingIntervalSecondsLTE(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldPollingIntervalSeconds, v))
}

// MinValueEQ applies the EQ predicate on the "min_value" field.
func MinValueEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldMinValue, v))
}

// MinValueNEQ applies the NEQ predicate on the "min_value" field.
func MinValueNEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldMinValue, v))
}

// MinValueIn applies the In predicate on the "min_value" field.
func MinValueIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldMinValue, vs...))
}

// MinValueNotIn applies the NotIn predicate on the "min_value" field.
func MinValueNotIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldMinValue, vs...))
}

// MinValueGT applies the GT predicate on the "min_value" field.
func MinValueGT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldMinValue, v))
}

// MinValueGTE applies the GTE predicate on the "min_value" field.
func MinValueGTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldMinValue, v))
}

// MinValueLT applies the LT predicate on the "min_value" field.
func MinValueLT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldMinValue, v))
}

// MinValueLTE applies the LTE predicate on the "min_value" field.
func MinValueLTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldMinValue, v))
}

// MinValueIsNil applies the IsNil predicate on the "min_value" field.
func MinValueIsNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIsNull(FieldMinValue))
}

// MinValueNotNil applies the NotNil predicate on the "min_value" field.
func MinValueNotNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotNull(FieldMinValue))
}

// MaxValueEQ applies the EQ predicate on the "max_value" field.
func MaxValueEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldMaxValue, v))
}

// MaxValueNEQ applies the NEQ predicate on the "max_value" field.
func MaxValueNEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldMaxValue, v))
}

// MaxValueIn applies the In predicate on the "max_value" field.
func MaxValueIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldMaxValue, vs...))
}

// MaxValueNotIn applies the NotIn predicate on the "max_value" field.
func MaxValueNotIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldMaxValue, vs...))
}

// MaxValueGT applies the GT predicate on the "max_value" field.
func MaxValueGT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldMaxValue, v))
}

// MaxValueGTE applies the GTE predicate on the "max_value" field.
func MaxValueGTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldMaxValue, v))
}

// MaxValueLT applies the LT predicate on the "max_value" field.
func MaxValueLT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldMaxValue, v))
}

// MaxValueLTE applies the LTE predicate on the "max_value" field.
func MaxValueLTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldMaxValue, v))
}

// MaxValueIsNil applies the IsNil predicate on the "max_value" field.
func MaxValueIsNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIsNull(FieldMaxValue))
}

// MaxValueNotNil applies the NotNil predicate on the "max_value" field.
func MaxValueNotNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotNull(FieldMaxValue))
}

// MeanValueEQ applies the EQ predicate on the "mean_value" field.
func MeanValueEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldMeanValue, v))
}

// MeanValueNEQ applies the NEQ predicate on the "mean_value" field.
func MeanValueNEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldMeanValue, v))
}

// MeanValueIn applies the In predicate on the "mean_value" field.
func MeanValueIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldMeanValue, vs...))
}

// MeanValueNotIn applies the NotIn predicate on the "mean_value" field.
func MeanValueNotIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldMeanValue, vs...))
}

// MeanValueGT applies the GT predicate on the "mean_value" field.
func MeanValueGT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldMeanValue, v))
}

// MeanValueGTE applies the GTE predicate on the "mean_value" field.
func MeanValueGTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldMeanValue, v))
}

// MeanValueLT applies the LT predicate on the "mean_value" field.
func MeanValueLT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldMeanValue, v))
}

// MeanValueLTE applies the LTE predicate on the "mean_value" field.
func MeanValueLTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldMeanValue, v))
}

// MeanValueIsNil applies the IsNil predicate on the "mean_value" field.
func MeanValueIsNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIsNull(FieldMeanValue))
}

// MeanValueNotNil applies the NotNil predicate on the "mean_value" field.
func MeanValueNotNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotNull(FieldMeanValue))
}

// StdDeviationEQ applies the EQ predicate on the "std_deviation" field.
func StdDeviationEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldStdDeviation, v))
}

// StdDeviationNEQ applies the NEQ predicate on the "std_deviation" field.
func StdDeviationNEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldStdDeviation, v))
}

// StdDeviationIn applies the In predicate on the "std_deviation" field.
func StdDeviationIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldStdDeviation, vs...))
}

// StdDeviationNotIn applies the NotIn predicate on the "std_deviation" field.
func StdDeviationNotIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldStdDeviation, vs...))
}

// StdDeviationGT applies the GT predicate on the "std_deviation" field.
func StdDeviationGT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldStdDeviation, v))
}

// StdDeviationGTE applies the GTE predicate on the "std_deviation" field.
func StdDeviationGTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldStdDeviation, v))
}

// StdDeviationLT applies the LT predicate on the "std_deviation" field.
func StdDeviationLT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldStdDeviation, v))
}

// StdDeviationLTE applies the LTE predicate on the "std_deviation" field.
func StdDeviationLTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldStdDeviation, v))
}

// StdDeviationIsNil applies the IsNil predicate on the "std_deviation" field.
func StdDeviationIsNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIsNull(FieldStdDeviation))
}

// StdDeviationNotNil applies the NotNil predicate on the "std_deviation" field.
func StdDeviationNotNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotNull(FieldStdDeviation))
}

// DriftFactorEQ applies the EQ predicate on the "drift_factor" field.
func DriftFactorEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldDriftFactor, v))
}

// DriftFactorNEQ applies the NEQ predicate on the "drift_factor" field.
func DriftFactorNEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldDriftFactor, v))
}

// DriftFactorIn applies the In predicate on the "drift_factor" field.
func DriftFactorIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldDriftFactor, vs...))
}

// DriftFactorNotIn applies the NotIn predicate on the "drift_factor" field.
func DriftFactorNotIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldDriftFactor, vs...))
}

// DriftFactorGT applies the GT predicate on the "drift_factor" field.
func DriftFactorGT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldDriftFactor, v))
}

// DriftFactorGTE applies the GTE predicate on the "drift_factor" field.
func DriftFactorGTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldDriftFactor, v))
}

// DriftFactorLT applies the LT predicate on the "drift_factor" field.
func DriftFactorLT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldDriftFactor, v))
}

// DriftFactorLTE applies the LTE predicate on the "drift_factor" field.
func DriftFactorLTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldDriftFactor, v))
}

// SeasonalVariationEQ applies the EQ predicate on the "seasonal_variation" field.
func SeasonalVariationEQ(v bool) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldSeasonalVariation, v))
}

// SeasonalVariationNEQ applies the NEQ predicate on the "seasonal_variation" field.
func SeasonalVariationNEQ(v bool) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldSeasonalVariation, v))
}

// CyclePeriodSecondsEQ applies the EQ predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsEQ(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldCyclePeriodSeconds, v))
}

// CyclePeriodSecondsNEQ applies the NEQ predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsNEQ(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldCyclePeriodSeconds, v))
}

// CyclePeriodSecondsIn applies the In predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsIn(vs ...int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldCyclePeriodSeconds, vs...))
}

// CyclePeriodSecondsNotIn applies the NotIn predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsNotIn(vs ...int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldCyclePeriodSeconds, vs...))
}

// CyclePeriodSecondsGT applies the GT predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsGT(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldCyclePeriodSeconds, v))
}

// CyclePeriodSecondsGTE applies the GTE predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsGTE(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldCyclePeriodSeconds, v))
}

// CyclePeriodSecondsLT applies the LT predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsLT(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldCyclePeriodSeconds, v))
}

// CyclePeriodSecondsLTE applies the LTE predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsLTE(v int) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldCyclePeriodSeconds, v))
}

// CyclePeriodSecondsIsNil applies the IsNil predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsIsNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIsNull(FieldCyclePeriodSeconds))
}

// CyclePeriodSecondsNotNil applies the NotNil predicate on the "cycle_period_seconds" field.
func CyclePeriodSecondsNotNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotNull(FieldCyclePeriodSeconds))
}

// NoiseFactorEQ applies the EQ predicate on the "noise_factor" field.
func NoiseFactorEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldEQ(FieldNoiseFactor, v))
}

// NoiseFactorNEQ applies the NEQ predicate on the "noise_factor" field.
func NoiseFactorNEQ(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNEQ(FieldNoiseFactor, v))
}

// NoiseFactorIn applies the In predicate on the "noise_factor" field.
func NoiseFactorIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIn(FieldNoiseFactor, vs...))
}

// NoiseFactorNotIn applies the NotIn predicate on the "noise_factor" field.
func NoiseFactorNotIn(vs ...float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotIn(FieldNoiseFactor, vs...))
}

// NoiseFactorGT applies the GT predicate on the "noise_factor" field.
func NoiseFactorGT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGT(FieldNoiseFactor, v))
}

// NoiseFactorGTE applies the GTE predicate on the "noise_factor" field.
func NoiseFactorGTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldGTE(FieldNoiseFactor, v))
}

// NoiseFactorLT applies the LT predicate on the "noise_factor" field.
func NoiseFactorLT(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLT(FieldNoiseFactor, v))
}

// NoiseFactorLTE applies the LTE predicate on the "noise_factor" field.
func NoiseFactorLTE(v float64) predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldLTE(FieldNoiseFactor, v))
}

// PossibleValuesIsNil applies the IsNil predicate on the "possible_values" field.
func PossibleValuesIsNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIsNull(FieldPossibleValues))
}

// PossibleValuesNotNil applies the NotNil predicate on the "possible_values" field.
func PossibleValuesNotNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotNull(FieldPossibleValues))
}

// AnomalyConfigIsNil applies the IsNil predicate on the "anomaly_config" field.
func AnomalyConfigIsNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldIsNull(FieldAnomalyConfig))
}

// AnomalyConfigNotNil applies the NotNil predicate on the "anomaly_config" field.
func AnomalyConfigNotNil() predicate.SensorSettings {
	return predicate.SensorSettings(sql.FieldNotNull(FieldAnomalyConfig))
}

// HasSensorType applies the HasEdge predicate on the "sensor_type" edge.
func HasSensorType() predicate.SensorSettings {
	return predicate.SensorSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SensorTypeTable, SensorTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSensorTypeWith applies the HasEdge predicate on the "sensor_type" edge with a given conditions (other predicates).
func HasSensorTypeWith(preds ...predicate.SensorType) predicate.SensorSettings {
	return predicate.SensorSettings(func(s *sql.Selector) {
		step := newSensorTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SensorSettings) predicate.SensorSettings {
	return predicate.SensorSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SensorSettings) predicate.SensorSettings {
	return predicate.SensorSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SensorSettings) predicate.SensorSettings {
	return predicate.SensorSettings(sql.NotPredicates(p))
}
