// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SensorsColumns holds the columns for the "sensors" table.
	SensorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "last_updated", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "sensor_type", Type: field.TypeInt},
	}
	// SensorsTable holds the schema information for the "sensors" table.
	SensorsTable = &schema.Table{
		Name:       "sensors",
		Columns:    SensorsColumns,
		PrimaryKey: []*schema.Column{SensorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sensors_sensor_types_type",
				Columns:    []*schema.Column{SensorsColumns[8]},
				RefColumns: []*schema.Column{SensorTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SensorSettingsColumns holds the columns for the "sensor_settings" table.
	SensorSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "polling_interval_seconds", Type: field.TypeInt, Default: 60},
		{Name: "min_value", Type: field.TypeFloat64, Nullable: true},
		{Name: "max_value", Type: field.TypeFloat64, Nullable: true},
		{Name: "mean_value", Type: field.TypeFloat64, Nullable: true},
		{Name: "std_deviation", Type: field.TypeFloat64, Nullable: true},
		{Name: "drift_factor", Type: field.TypeFloat64, Default: 0},
		{Name: "seasonal_variation", Type: field.TypeBool, Default: false},
		{Name: "cycle_period_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "noise_factor", Type: field.TypeFloat64, Default: 0.05},
		{Name: "possible_values", Type: field.TypeJSON, Nullable: true},
		{Name: "anomaly_config", Type: field.TypeJSON, Nullable: true},
		{Name: "sensor_type_settings", Type: field.TypeInt, Unique: true},
	}
	// SensorSettingsTable holds the schema information for the "sensor_settings" table.
	SensorSettingsTable = &schema.Table{
		Name:       "sensor_settings",
		Columns:    SensorSettingsColumns,
		PrimaryKey: []*schema.Column{SensorSettingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sensor_settings_sensor_types_settings",
				Columns:    []*schema.Column{SensorSettingsColumns[12]},
				RefColumns: []*schema.Column{SensorTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SensorTypesColumns holds the columns for the "sensor_types" table.
	SensorTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "model", Type: field.TypeString},
		{Name: "manufacturer", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// SensorTypesTable holds the schema information for the "sensor_types" table.
	SensorTypesTable = &schema.Table{
		Name:       "sensor_types",
		Columns:    SensorTypesColumns,
		PrimaryKey: []*schema.Column{SensorTypesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SensorsTable,
		SensorSettingsTable,
		SensorTypesTable,
	}
)

func init() {
	SensorsTable.ForeignKeys[0].RefTable = SensorTypesTable
	SensorSettingsTable.ForeignKeys[0].RefTable = SensorTypesTable
}
