// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Sensor is the predicate function for sensor builders.
type Sensor func(*sql.Selector)

// SensorSettings is the predicate function for sensorsettings builders.
type SensorSettings func(*sql.Selector)

// SensorType is the predicate function for sensortype builders.
type SensorType func(*sql.Selector)
